### ISSUE TITLE
[Extension]: prompt-travel not work anymore

### ISSUE THREAD

**Issue by sebaxakerhtc** [vladmandic/automatic#1073]
### Issue Description

Installed prompt-travel, but it doesn't work because of:
`'Options' object has no attribute 'enable_pnginfo'`

Full output from terminal:
```
Traceback (most recent call last) ────────────────────────────────────────────────────────────╮
│ D:\automatic\modules\call_queue.py:33 in f                                                                                                               │
│                                                                                                                                                          │
│    32 │   │   │   try:                                                                                                                                   │
│ ❱  33 │   │   │   │   res = func(*args, **kwargs)                                                                                                        │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                                                              │
│                                                                                                                                                          │
│ D:\automatic\modules\txt2img.py:54 in txt2img                                                                                                            │
│                                                                                                                                                          │
│   53 │   p.script_args = args                                                                                                                            │
│ ❱ 54 │   processed = modules.scripts.scripts_txt2img.run(p, *args)                                                                                       │
│   55 │   if processed is None:                                                                                                                           │
│                                                                                                                                                          │
│                                                                 ... 4 frames hidden ...                                                                  │
│                                                                                                                                                          │
│ D:\automatic\extensions\stable-diffusion-webui-prompt-travel\scripts\prompt_travel.py:314 in process_images_cond_to_image                                │
│                                                                                                                                                          │
│    313 │   │   │   infotexts.append(text)                                                                                                                │
│ ❱  314 │   │   │   if opts.enable_pnginfo:                                                                                                               │
│    315 │   │   │   │   image.info["parameters"] = text                                                                                                   │
│                                                                                                                                                          │
│ D:\automatic\modules\shared.py:511 in __getattr__                                                                                                        │
│                                                                                                                                                          │
│   510 │   │   │   return self.data_labels[item].default                                                                                                  │
│ ❱ 511 │   │   return super(Options, self).__getattribute__(item)                                                                                         │
│   512                                                                                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Options' object has no attribute 'enable_pnginfo'
```
in original auto1111 extension works normally

### Version Platform Description

Windows, Mozilla Firefox

### URL link of the extension

https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel

**Comment by sebaxakerhtc** [comment]
For now eb03fce3e4733ef98f8233e5170c12938502674d - latest known working

**Comment by vladmandic** [comment]
fixed via adding a compatibility option.

**Comment by sebaxakerhtc** [comment]
Why this is closed?
Still the same error:
`AttributeError: 'Options' object has no attribute 'enable_pnginfo'`


> fixed via adding a compatibility option.

Can you please provide a commit with added `enable_pnginfo`?
Thank you!

**Comment by sebaxakerhtc** [comment]
Restart was needed after update
