### ISSUE TITLE
[Extension]: controlnet with adetailer

### ISSUE THREAD

**Issue by Antigone84** [vladmandic/automatic#1116]
### Issue Description

Adetailer (after detail extension) does not work with controlnet active, works on automatic1111. **currently it does not work, so maybe it was an update to one of them**

AssertionError: ControlNet Error: Failed to detect whether an instance is cond or uncond!
mediapipe: 1 detected.
  0%|                                                                                            | 0/7 [00:00<?, ?it/s]
15:34:22-853965 ERROR    Running script postprocess image: D:\automatic\extensions\adetailer\scripts\!adetailer.py:
                         AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\scripts.py:422 in postprocess_image                                                             │
│                                                                                                                      │
│   421 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 422 │   │   │   │   script.postprocess_image(p, pp, *args)                                                         │
│   423 │   │   │   except Exception as e:

### Version Platform Description

Windows 11, current vlad version, current automatic1111

### URL link of the extension

https://github.com/Bing-su/adetailer

**Comment by vladmandic** [comment]
resolved?

**Comment by Antigone84** [comment]
Not resolved, but it was discovered to be something happening with Adetailer, not exclusive to Vladfusion
