### ISSUE TITLE
[Issue]: refreshing extension list in browser breaks the system. [TypeError]

### ISSUE THREAD

**Issue by Shouri14** [vladmandic/automatic#1485]
### Issue Description

Refreshing extension list seems to have caused an issue.

In a fresh clone, 
 - Launched the webUI
 - In extensions tab, clicked on refresh extensions list.
 - Only have built-in extensions
 
It broke something. Closing webUI doesn't resolve it for further attempts.
When I try to launch webUI again, it fails with below trace.

<img width="1653" alt="image" src="https://github.com/vladmandic/automatic/assets/37922572/99de1662-3c0c-4540-b634-56eb2e55536f">

Needs a fresh install to resolve it, but touching the extensions tab caused the same issue again when I tried updating the extensions.

### Version Platform Description

20:41:10-530893 INFO     Starting SD.Next
20:41:10-532486 INFO     Python 3.10.6 on Linux
20:41:10-534129 INFO     Version: c02ccc4f Tue Jun 20 13:49:00 2023 +0300
20:41:10-820310 INFO     nVidia CUDA toolkit detected
20:41:11-368043 INFO     Torch 2.0.1+cu118
20:41:11-577097 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:41:11-609763 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
20:41:11-616207 INFO     Enabled extensions-builtin: ['stable-diffusion-webui-images-browser', 'sd-webui-agent-scheduler', 'clip-interrogator-ext',
                         'ScuNET', 'stable-diffusion-webui-rembg', 'sd-extension-system-info', 'SwinIR', 'a1111-sd-webui-lycoris', 'LDSR', 'Lora',
                         'sd-dynamic-thresholding', 'sd-webui-controlnet', 'multidiffusion-upscaler-for-automatic1111']
20:41:11-617308 INFO     Enabled extensions: []
20:41:11-617803 INFO     Verifying requirements
20:41:11-623771 INFO     Verifying packages
20:41:11-624496 INFO     Installing repositories
20:41:12-560381 INFO     Installing submodules
20:41:12-641429 INFO     Updating submodules
20:41:19-830748 INFO     Extensions enabled: ['stable-diffusion-webui-images-browser', 'sd-webui-agent-scheduler', 'clip-interrogator-ext', 'ScuNET',
                         'stable-diffusion-webui-rembg', 'sd-extension-system-info', 'SwinIR', 'a1111-sd-webui-lycoris', 'LDSR', 'Lora',
                         'sd-dynamic-thresholding', 'sd-webui-controlnet', 'multidiffusion-upscaler-for-automatic1111']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Try deleting html/extensions.json to force a refresh.

**Comment by ledeni00** [comment]
> 

I have the same problem.
deleting html/extensions.json allowed it to start again, but after refresh extension list, typError comes back.

**Comment by SouthbayJay** [comment]
I have the same problem but deleting html/extensions.json did let me get the UI back up and running.

**Comment by Shouri14** [comment]
I debugged a little to see if I can find what's going on and looks like the problem is when it is executing extension `sd-extension-system-info`

`ui_extensions.py` is trying go through each extension from the extension_list and grab if there's any `tags` for the extension.
@lines `333-334`
<img width="327" alt="image" src="https://github.com/vladmandic/automatic/assets/37922572/79fbef12-3938-4f20-93d8-e4ad21aacf25">

For other extensions, `tags` either has data or is an empty `list`.
But for `sd-extension-system-info`, `tags` is an empty string.
Hence in line `334`, it is throwing an error that we are trying to concatenate a string, instead of list of strings.

<img width="1676" alt="image" src="https://github.com/vladmandic/automatic/assets/37922572/d19c47ea-cbee-413c-802f-3c547a8adfd2">


Haven't looked at from where this data is coming but hope this helps.

**Comment by Shouri14** [comment]
Data is from `html/extensions.json`

<img width="629" alt="image" src="https://github.com/vladmandic/automatic/assets/37922572/10144400-b83a-4806-8b27-a7cf16c549e5">

This is only occurrence of empty `tags` string in the file.
Updating this should solve the problem.

**Comment by RchGrav** [comment]
Just edit it to this until the repo is fixed.   it should be a string like this...

`  {
    "name": "sd-extension-system-info",
    "url": "https://github.com/vladmandic/sd-extension-system-info.git",
    "description": "System Info Extension for SD WebUI",
    "tags": [],
    "added": null,
    "created": "2023-01-14T16:40:39.000Z",
    "pushed": "2023-06-21T19:23:27.000Z",
    "long": "vladmandic/sd-extension-system-info",
    "size": 61182,
    "stars": 137,
    "issues": 0,
    "branch": "main",
    "updated": "2023-06-21T19:23:25Z",
    "commits": 953,
    "status": "verified",
    "note": ""
  },`

**Comment by RchGrav** [comment]
This should make it work, I chose system since it seems to be its purpose.   Any arbitrary tag should fix it, make sure it's an array using the square brackets or just copy and paste this code below and replace it in your extensions.json.  It allows the extensions list to load.   
```
  {
    "name": "sd-extension-system-info",
    "url": "https://github.com/vladmandic/sd-extension-system-info.git",
    "description": "System Info Extension for SD WebUI",
    "tags": [
    "System"
    ],
    "added": null,
    "created": "2023-01-14T16:40:39.000Z",
    "pushed": "2023-06-21T19:23:27.000Z",
    "long": "vladmandic/sd-extension-system-info",
    "size": 61182,
    "stars": 137,
    "issues": 0,
    "branch": "main",
    "updated": "2023-06-21T19:23:25Z",
    "commits": 953,
    "status": "verified",
    "note": ""
  },
  ```

**Comment by ronbere** [comment]
> This should make it work, I chose system since it seems to be its purpose. Any arbitrary tag should fix it, make sure it's an array using the square brackets or just copy and paste this code below and replace it in your extensions.json. It allows the extensions list to load.
> 
> ```
>   {
>     "name": "sd-extension-system-info",
>     "url": "https://github.com/vladmandic/sd-extension-system-info.git",
>     "description": "System Info Extension for SD WebUI",
>     "tags": [
>     "System"
>     ],
>     "added": null,
>     "created": "2023-01-14T16:40:39.000Z",
>     "pushed": "2023-06-21T19:23:27.000Z",
>     "long": "vladmandic/sd-extension-system-info",
>     "size": 61182,
>     "stars": 137,
>     "issues": 0,
>     "branch": "main",
>     "updated": "2023-06-21T19:23:25Z",
>     "commits": 953,
>     "status": "verified",
>     "note": ""
>   },
> ```

it works, but if we try a refresh extension list again, the issue persists, so this is not yet the solution unfortunately

**Comment by vladmandic** [comment]
fixed.

**Comment by chuckkay** [comment]
> fixed.

I think the problem is back. deleting extensions.json helped last time, 
but now the problem is back but this time with 4 built-in extensions :

sd-extension-system-info
sd-webui-controlnet
sd-webui-agent-scheduler
sd-dynamic-thresholding
