### ISSUE TITLE
[Issue]: Process Image - Parameters not reproducing newlines

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#1561]
### Issue Description

Hello,
it seems something broke, the parameters are all in a single line.
See the initial issue I opened about this a few months ago, the behaviour is the same #273 .

### Version Platform Description

Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
if processed imageinfo is then transferred to txt2img or img2img prompt, how does it look?

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Same as the old issue, if I do that the prompt has the correct newlines.

**Comment by vladmandic** [comment]
fixed in dev, will be posted to master later this week.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Thank you.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
I have noticed something, figured I'd mention it.
At the moment of this post it's still broken, however if I generate anything on the "process image" tab, any image I load into there afterwards will have parameters with working newlines, and will keep working until I close the tab.
