### ISSUE TITLE
[Issue]: XYZ Script error

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1585]
### Issue Description

XYZ Script errors out before created the grid;

```
15:34:03-085127 ERROR    gradio call: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\automatic\modules\call_queue.py:34 in f                                                                          │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ E:\automatic\modules\txt2img.py:54 in txt2img                                                                       │
│                                                                                                                     │
│   53 │   p.script_args = args                                                                                       │
│ > 54 │   processed = modules.scripts.scripts_txt2img.run(p, *args)                                                  │
│   55 │   if processed is None:                                                                                      │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ E:\automatic\modules\images.py:182 in draw_grid_annotations                                                         │
│                                                                                                                     │
│   181 │   │   y = pad_top / 2 - hor_text_heights[col] / 2                                                           │
│ > 182 │   │   draw_texts(d, x, y, hor_texts[col], fnt, fontsize)                                                    │
│   183 │   for row in range(rows):                                                                                   │
│                                                                                                                     │
│ E:\automatic\modules\images.py:140 in draw_texts                                                                    │
│                                                                                                                     │
│   139 │   │   │   fontsize = initial_fontsize                                                                       │
│ > 140 │   │   │   while drawing.multiline_textsize(line.text, font=fnt)[0] > line.allowed_widt                      │
│   141 │   │   │   │   fontsize -= 1                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize'
```

### Version Platform Description

Starting SD.Next
Python 3.10.11 on Windows
Version: 422c60c7 Wed Jul 5 20:49:39 2023 +0300
Using DirectML Backend
Torch 2.0.1+cpu
Torch backend: DirectML (torch-directml 0.2.0.dev230426)
Torch detected GPU: AMD Radeon RX 6600 XT

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
pillow changed several functions in the latest release 10.0.0 which are not compatibile.
for now, i'll lock pillow version to 9.5.0.

fixed in dev, should be merged to master by tomorrow.

**Comment by Neveraxme** [comment]
I got this error in Google Colab, Pillow version is 9.4.0. I tried upadate to version 9.5.0 but the error is still the same. Sorry for bad english. I'm not really know codes, just a curious guy.

**Comment by EismeisterGH** [comment]
**First thank you for your excellent work!**

When I try to use the X/Y/Z script in Stability Matrix Automatic1111 I get the same error message:

attributeerror: 'imagedraw' object has no attribute 'multiline_textsize'

I have 2 versions of Pillow in the directory, but I'm not sure if it has anything to do with this:

![image](https://github.com/vladmandic/automatic/assets/155578972/1af0ff3a-51b2-45e8-a33e-b25195a7c69e)

...\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\Lib\site-packages

How can I install Pillow version 9.5.0?

Many thanks in advance

**Comment by vladmandic** [comment]
this is not automatic1111. this repo has been updated to use pillow 10 and xyz grid script is also updated to be compatible with it.

**Comment by EismeisterGH** [comment]
Maybe I have shot my automatic1111.

![image](https://github.com/vladmandic/automatic/assets/155578972/d5529d45-59d8-49f6-9441-be1a3c48de52)

**Comment by vladmandic** [comment]
the screenshot is NOT this application to start with. this is SD.Next, that's not it.
