### ISSUE TITLE
[Issue]: Extra networks, lyco-patch-lora shows Lora folder on startup, LyCORIS folder after refresh.

### ISSUE THREAD

**Issue by SoraEnkai** [vladmandic/automatic#1612]
### Issue Description

Reproducible on latest master as of now (commit `db30f5f`).
Tested with `--safe` to rule out external extensions.

Didn't see an issue with `Use LyCoris handler for all Lora types` enabled specifically.
This is with default folder paths.

Steps to reproduce:
1. Enable `lyco-patch-lora`.
2. Fully restart SD.Next
3. Open Extra Networks `LyCORIS` tab.

On first load, no Loras/LyCORIS are shown if `Lora` folder is empty.
Files are shown from `Lora` folder if `Lora` folder is not empty however.

Clicking `Refresh` button shows files from `LyCORIS` folder.
Note: Folders in sidebar are shown from `LyCORIS` folder on first load.

![Screenshot 2023-07-08 232944](https://github.com/vladmandic/automatic/assets/39128897/3525f796-0882-4c60-be45-8315b3c2dba4)

![Screenshot 2023-07-08 233007](https://github.com/vladmandic/automatic/assets/39128897/73674b12-67b2-4810-8b08-8acbab0d0ae7)

### Version Platform Description

23:28:52-574392 INFO     Starting SD.Next
23:28:52-578394 INFO     Python 3.10.6 on Windows
23:28:52-610448 INFO     Version: db30f5fa Sat Jul 8 14:22:51 2023 -0400
23:28:53-054221 INFO     nVidia CUDA toolkit detected
23:28:54-267970 INFO     Torch 2.0.1+cu118
23:28:54-283755 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:28:54-285753 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
23:28:54-400497 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:28:54-409529 INFO     No changes detected: Quick launch active
23:28:54-410526 INFO     Running in safe mode without user extensions
23:28:54-416043 INFO     Extension preload: 0.0s D:\AI_STUFF\automatic\extensions-builtin
23:28:54-429559 INFO     Server arguments: ['--upgrade', '--safe']
23:28:58-942060 INFO     Pipeline: Backend.ORIGINAL
No module 'xformers'. Proceeding without it.
23:29:00-125852 INFO     Libraries loaded
23:29:00-128129 INFO     Using data path: D:\AI_STUFF\automatic
23:29:00-137859 INFO     Available VAEs: D:\AI_STUFF\automatic\models\VAE 12
23:29:00-157400 INFO     Available models: D:\AI_STUFF\automatic\models\Stable-diffusion 28
23:29:02-746047 INFO     ControlNet v1.1.231
ControlNet v1.1.231
ControlNet preprocessor location: D:\AI_STUFF\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
23:29:02-872563 INFO     ControlNet v1.1.231
ControlNet v1.1.231
23:29:04-704042 INFO     Loading UI theme: name=nota-ai/theme style=Auto
23:29:04-707043 WARNING  Triggered lyco-patch-lora, will take lora_dir and <lora> format.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Thanks for the actual detailed steps, that helps a lot - and I have an idea what's the root cause, expect fix by Monday.

**Comment by vladmandic** [comment]
should be fixed now.

**Comment by SoraEnkai** [comment]
Tried again on [a16eee1](https://github.com/vladmandic/automatic/commit/a16eee1504173aae2052b850702b6297e41e0500), but the issue still persists.

On first load it's still empty.
![Screenshot 2023-07-09 183513](https://github.com/vladmandic/automatic/assets/39128897/cbbd4e60-f5ca-44cb-b79e-25ad4535b728)

**Comment by vladmandic** [comment]
there may be some misunderstanding here, if `lyco_patch_lora` is enabled, lycoris folder is used at all and lyco will look inside lora_dir instead.

**Comment by SoraEnkai** [comment]
I wrote to you on discord since it would be faster i think, but basically:

What happens is with `lyco_patch_lora` enabled, is that for example if i have all my Lora/Lyco in Lora folder, it will show them with broken thumbnails on startup.

After refreshing it shows nothing, it also doesn't show the folders in sidebar.

If i have them all in LyCORIS folder, on load it shows nothing, but after refreshing it shows them correctly with thumbnails etc.
Which is where the confusion happens, if it's supposed to use Lora folder, it doesn't do that properly right now.

This is currently what i'm experiencing:

This is with Lora/Lyco in `Lora` folder (LyCORIS folder is empty)
![Screenshot 2023-07-09 190525](https://github.com/vladmandic/automatic/assets/39128897/4edbd1e0-dc23-43a1-8b9c-567440b6131f)

This is after refresh.
![Screenshot 2023-07-09 190540](https://github.com/vladmandic/automatic/assets/39128897/6e272634-4d65-4b53-8775-5967c1e95145)

And now in `LyCORIS` folder (Lora folder is empty)
![Screenshot 2023-07-09 190821](https://github.com/vladmandic/automatic/assets/39128897/e0d4c179-396a-43da-b976-d46591f72b7e)

And after refresh:
![Screenshot 2023-07-09 190841](https://github.com/vladmandic/automatic/assets/39128897/6d4c1ca2-ff9b-4525-872c-9d0ffec3344a)

If i misunderstood something or you need more info, you can also ping me on discord.

**Comment by vladmandic** [comment]
Do you also set disable builtin lora when enabling lyco patch lora?

**Comment by SoraEnkai** [comment]
No, other settings are default:
![Screenshot 2023-07-09 191452](https://github.com/vladmandic/automatic/assets/39128897/4d35ddcc-82b7-4dce-9818-6163345ee053)

**Comment by vladmandic** [comment]
Those two settings are intended to go together (in reality, second shouldnt even exist, I'll remove it in the future). Can you try with disable built in lora?

**Comment by SoraEnkai** [comment]
Same exact behaviour, just now `Lora` extension is disabled.

**Comment by vladmandic** [comment]
OK, I'll take a look.

**Comment by slimeqslimedog** [comment]
Just to give my two cents, I'm seeing this same issue with thumbnails suddenly not loading properly too, and it happens in all tabs, not just LoRA/LyCORIS. I don't know what caused it, either -- they just happened to work at one point, and then didn't the next day.
What's odd is that _some_ thumbnails seem to work fine while others do not, and when inspect the page and check the requests being sent, nothing seems to stand out between ones that work and ones that don't.

As an example:
*  `http://localhost:7860/sd_extra_networks/thumb?filename=X%3A/automatic/models/Lora/Character/Toon/Daria%20-%20Daria%20Morgendorffer%20-%2092089.thumb.jpg&mtime=1687986822.407657` is a thumbnail that works just fine on my system.
* `http://localhost:7860/sd_extra_networks/thumb?filename=X%3A/automatic/models/Lora/Character/Toon/Boondocks%20-%20Huey%20Freeman%20-%20TheGooder%20-%20103703.thumb.jpg&mtime=1688730290.7401056` is a thumbnail that fails and returns the content `{"error":"File cannot be fetched: X:/automatic/models/Lora/Character/Toon/Boondocks - Huey Freeman - TheGooder - 103703.thumb.jpg. Must be in one of directories registered by extra pages."}`

Both files are definitely present, and both are valid PNG files.

For reference:
* I'm on commit `a844a83d9daa9987295932c0db391ec7be5f2d32`.
* I have "Use LyCORIS handler for all Lora types" and "Disable built-in Lora handler" enabled, but toggling them doesn't make a difference, nor does clicking the refresh button in the extra networks window. 
* If I delete a "thumb.jpg" file from the Lora directory, it is _not_ recreated when I restart the server.
* If I delete one from another directory such as "embeddings", it _is_ recreated when I restart the server, and the new thumb appears to be correct in File Explorer, but it still doesn't work in the extra networks window.

I hope this helps with troubleshooting a bit!

**Comment by mart-hill** [comment]
On my side, when I used "Use LyCoris handler" and "disable built-in Lora handler" and rebooted the UI, it completely eradicated Lora support, and every extension using LoRAs "protested" because of that. It was just out of curiosity, so I reverted these settings later on. 🙂 
It was on one of commits from two days ago, I think. I didn't test it on newest commit yet.

Now, when I use "Kohya method", and nothing else (another test), the parser reacts only on <lyco:xxxx:y>, <lora> gives known `Exception: The size of tensor a (51) must match the size of tensor b (49) at non-singleton dimension 3` 🙂

**Comment by vladmandic** [comment]
> On my side, when I used "Use LyCoris handler" and "disable built-in Lora handler" together and rebooted the UI, it completely eradicated Lora support, and every extension using LoRAs "protested" because of that

with the rest i might agree with, but this statement is misleading at best.
with those statements, lora works perfecly (actually much better and wider support and no activation issues which normal lora is known for).  
what doesn't work are extensions that try to patch directly into code since that code is no longer loaded.

**Comment by mart-hill** [comment]
Ah, so it's the "Additional Networks" extension's "job"? The disabling thing?
![image](https://github.com/vladmandic/automatic/assets/55754730/89184cbf-f6cc-4039-83a1-9da44565ab4a)

So it's probably best to disable it. :)

**Comment by vladmandic** [comment]
yeah, additional networks extension cannot work with built-in lora disabled as all it does it modifies built-in code - quite heavily.

**Comment by mart-hill** [comment]
Indeed, this extension did "protest", but also everything else did, beginning with the UI itself, since I literally disabled LoRA, apparently.

**Comment by vladmandic** [comment]
what is the current status of this issue? there are multiple users reporing similar but not identical issues.

**Comment by eadnams22** [comment]
My lycoris tab just com-lately disappears, and they won’t load from text prompts, unsure why, seems almost random when closing and restarting.

**Comment by vladmandic** [comment]
@eadnams22 ok, so new user, new symptoms and you haven't documented much, just a single sentence.

**Comment by eadnams22** [comment]
> @eadnams22 ok, so new user, new symptoms and you haven't documented much, just a single sentence.

Yup, still troubleshooting and trying to make it repeatable before I go any further.

**Comment by SoraEnkai** [comment]
@vladmandic Hey, tested again on `33528765` with same settings and `--safe`, same behaviour as on my previous comment
https://github.com/vladmandic/automatic/issues/1612#issuecomment-1627761089

**Comment by vladmandic** [comment]
as i said before, `lyco_patch_lora` is intended to be used together with `lora_disable`. 
what happens then?

**Comment by SoraEnkai** [comment]
Sorry, should've clarified same settings as in both enabled
![image](https://github.com/vladmandic/automatic/assets/39128897/0efeb8d1-1c6e-49d3-a085-82a8f1310a3b)

**Comment by Bodzijun** [comment]
ERROR    Extra networks page error: 'str' object has no attribute 'keys', 
In webUi lora tab is empty..
How fix it?

**Comment by vladmandic** [comment]
first, that is a completely separate issue. so create new issue.
second, show log, your message does not help at all.

**Comment by vladmandic** [comment]
fixed.
