### ISSUE TITLE
[Issue]: "Resize by" option does nothing

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#1865]
### Issue Description

Hello,
in the "From Image" tab you can resize to a specific size, or you can use "Resize by" to make the program automatically calculate the new size based on the multiplier you enter.
This doesn't work anymore.
It doesn't give any errors and the output size shown on the UI is correct, but the outputted image is the same size as the input.

### Version Platform Description

version: 77de9cd0 Fri Jul 28 23:18:28 2023 +0900

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
and manual resize to specified size works fine?

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Uh, I tried it just now and both resizing options don't work and just keep the input's resolution.
But I think at some point I tried it and it was working with manually configured sizes, because sometimes I forget to re-enter the sizes after inpainting and got img2img outputs with bad resolutions (user error here, not the program's fault). I didn't make a note of it though so I wouldn't swear on it.

**Comment by vladmandic** [comment]
i'll check, but it might be a bit longer than usual due to my travels.

**Comment by vladmandic** [comment]
should be fixed.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Still not working on version " 66394c8c Mon Aug 14 21:54:21 2023 +0300 "
Tried both manually setting a size and using a multiplier, still keeps the same size as the input.

**Comment by vladmandic** [comment]
i just tested and it works. note that you must set resize method - default is none.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
You're right, I manually move it to "Resize fixed" and I can confirm it works now, I didn't notice the names changed so my ui defaults file wasn't working anymore.
I have changed my defaults too now.
