### ISSUE TITLE
[Issue]: Switching refiner to None leads to error

### ISSUE THREAD

**Issue by sebaxakerhtc** [vladmandic/automatic#2072]
### Issue Description

When I use refiner for generation all works fine. But then I switch it to None, disabled second pass and trying to generate image and it gives me: "Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)"
If I need it to work again - I should close cmd with webui and restart it again

### Version Platform Description

Python 3.10.11 on Windows (native)
Version: 0512e297

### Relevant log output

```shell
15:26:41-413545 ERROR    Exception: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
15:26:41-414567 ERROR    Arguments: args=('task(os7xusumb7dq960)', 'gymnast girl at Olympic games', 'blurred, out of focus, disfigured, deformed, clothes', [], 30, 4, 4, True, False, False, 1, 4, 8, 6, 0.7, 1, -1.0,
                         -1.0, 0, 0, 0, 1024, 576, False, 0.15, 1, 'None', 30, 0, 0, 0.8, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False, False, 0,
                         False) kwargs={}
15:26:41-414567 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ D:\auto-latest\automatic\modules\call_queue.py:34 in f                                                                                                                                               │
│                                                                                                                                                                                                      │
│    33 │   │   │   try:                                                                                                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                                                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                                                                                                          │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\modules\txt2img.py:65 in txt2img                                                                                                                                            │
│                                                                                                                                                                                                      │
│   64 │   if processed is None:                                                                                                                                                                       │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                                                                                                                │
│   66 │   p.close()                                                                                                                                                                                   │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\modules\processing.py:565 in process_images                                                                                                                                 │
│                                                                                                                                                                                                      │
│    564 │   │   else:                                                                                                                                                                                 │
│ ❱  565 │   │   │   res = process_images_inner(p)                                                                                                                                                     │
│    566 │   finally:                                                                                                                                                                                  │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\modules\processing.py:728 in process_images_inner                                                                                                                           │
│                                                                                                                                                                                                      │
│    727 │   │   │   │   from modules.processing_diffusers import process_diffusers                                                                                                                    │
│ ❱  728 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                                                                                                      │
│    729                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\modules\processing_diffusers.py:235 in process_diffusers                                                                                                                    │
│                                                                                                                                                                                                      │
│   234 │                                                                                                                                                                                              │
│ ❱ 235 │   base_args = set_pipeline_args(                                                                                                                                                             │
│   236 │   │   model=shared.sd_model,                                                                                                                                                                 │
│                                                                                                                                                                                                      │
│                                                                                       ... 16 frames hidden ...                                                                                       │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                                                                                        │
│                                                                                                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                                                                                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                                                                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                                                                                                              │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:229 in forward                                                                                             │
│                                                                                                                                                                                                      │
│    228 │   │   if inputs_embeds is None:                                                                                                                                                             │
│ ❱  229 │   │   │   inputs_embeds = self.token_embedding(input_ids)                                                                                                                                   │
│    230                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                                                                                        │
│                                                                                                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                                                                                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                                                                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                                                                                                              │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\venv\lib\site-packages\torch\nn\modules\sparse.py:162 in forward                                                                                                            │
│                                                                                                                                                                                                      │
│   161 │   def forward(self, input: Tensor) -> Tensor:                                                                                                                                                │
│ ❱ 162 │   │   return F.embedding(                                                                                                                                                                    │
│   163 │   │   │   input, self.weight, self.padding_idx, self.max_norm,                                                                                                                               │
│                                                                                                                                                                                                      │
│ D:\auto-latest\automatic\venv\lib\site-packages\torch\nn\functional.py:2210 in embedding                                                                                                             │
│                                                                                                                                                                                                      │
│   2209 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                                                                                                                        │
│ ❱ 2210 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)                                                                                                            │
│   2211                                                                                                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
the traceback hints this happened during prompt encoding, not during model execution at all.
i've tried to reproduce, no luck.
if you can provide actual reproduction steps, i'd love to solve this.

**Comment by sebaxakerhtc** [comment]
Strange...
Maybe a little misunderstanding.
Steps to reproduce:
- start webui, diffusers backend
- choose refiner model
- activate second pass
- generate images
- uncheck second pass
- switch refiner to None
- try to generate images
- recieve error

**Comment by vladmandic** [comment]
Thanks for exact steps, I'll try it out.

**Comment by vladmandic** [comment]
should be fixed now.

**Comment by sebaxakerhtc** [comment]
Still the same on Version: 48c0ce9b
Will try to run with --reinstall

**Comment by vladmandic** [comment]
Reinstall takes time and it's not necessary here. 

I'll check again, but with latest update I couldn't reproduce. I'll reopen, give me a bit to think about this.

**Comment by vladmandic** [comment]
fixed, i hope this is it this time. i cant reproduce anymore.
