### ISSUE TITLE
SD.next: (GRADIO related) broken for me (doesnt save meta into images sometimes, copy to 'from text' doesnt work etc)

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#2078]
### Discussed in https://github.com/vladmandic/automatic/discussions/2077

<div type='discussions-op-text'>

<sup>Originally posted by **Tillerz** August 26, 2023</sup>
I right now updated ( 0f10a9ce ), and this is not working:

- When I change the prompt and then render an image, the METADATA underneath the image doesn't get updated with the changes (they are saved to the image though when clicking SAVE).

- [EDIT] And now the images also do not save with the METADATA, something is weird here. I did a --reinstall, that didn't give any improvements.

- Settings / show all:

![img](https://i.gyazo.com/467db0e1fa2f296b52fbe86d3b988d84.png)

- It also looks like "Secondary sampler" doesn't get restored when you start the UI and click the button to load the data from previous session.

- Loading an image in "Process Image" and then sending to "From Text" doesn't fill the prompt and negative prompt. Uh, I think it doesn't send ANYTHING over to the other tab. **EDIT**: Ok, it does work for OLDER images, it does not work with the metadata of images I rendered today ( version d48a13a1 ).</div>

**Comment by vladmandic** [comment]
metadata save is fixed.
restore values for gradio radio controls is fixed.
the rest i need to check.

**Comment by solsol360** [comment]
FYI, There is also a massive lag opening the UI after the Gradio update. Loading screen takes now 2 mins instead of 13 sec that was normal start up time for me. Running with --safe. Firefox and Edge report that the page is not responding at some point.
12:16:25-899197 INFO     Python 3.10.9 on Windows
12:16:25-949293 INFO     Version: 48c0ce9b Sun Aug 27 08:01:29 2023 +0000

**Comment by Boldor83** [comment]
the lag disappeared after doing 
git pull && git submodule update
disabeling extensions and removing scripts that caused error.
I still don't get text files when hitting save.

**Comment by vladmandic** [comment]
Saving text files only occurs if save image is enabled, that was always the case.

**Comment by Boldor83** [comment]
my save folder is full of images with text files before this occurred, they always were saved along when pressing the save button, now it only works when i enable "Always save all generated images", the save button is pretty useless when i only get text files when i save all files.

**Comment by Silanda** [comment]
This may be related so I'll post here instead of opening a new issue at the moment:

After recent updates SDNext doesn't seem to be saving the metadata into images processed by the Sd upscale script in img2img. It does when the script isn't used, however. I'm uncertain whether this is related, but I've also noticed that it's saving init images as .jpg despite both images and grids being set to save as .png.

**Comment by Silanda** [comment]
Cool, I'll open a new one.

**Comment by vladmandic** [comment]
@Tillerz can you check this item
> Loading an image in "Process Image" and then sending to "From Text" doesn't fill the prompt and negative prompt.

i cannot reproduce the problem.
the rest were valid and resolved.

**Comment by Tillerz** [comment]
I guess you can ignore the last one. I checked and it's only the metadata of images that I made with that broken version. These images seemed to have saved the metadata wrong. The data showed up in the UI when loading the image, but the "copy to other tab" didn't work. It works with older images. And I just tried with the new version, copying data from current images works again too.


But I have an addendum to the secondary sampler settings: they are not being saved to the image.

**Comment by vladmandic** [comment]
fixed addendum
