### ISSUE TITLE
[Issue]: Extensions have wrong width in UI

### ISSUE THREAD

**Issue by GodEmperor785** [vladmandic/automatic#2389]
### Issue Description

After updating today from version from 20.10.2023 (d8bb3496) to latest master extensions have wrong width in the UI in both txt2img and img2img and their UI elements seem to overlap with rest of UI, see screenshots below, ControlNet UI is much wider than standard txt2img options and overlaps with generated images:
![image](https://github.com/vladmandic/automatic/assets/32663080/3961e098-a106-499f-a116-61f67b4a838c)

And on img2img ("From Image") tab part of extension UI is not visible which makes using for example ControlNet harder as some elements are not visible:
![image](https://github.com/vladmandic/automatic/assets/32663080/c3594101-4fdb-484a-b010-31f010e03d52)

I tried with removing ui-config.json but same issue is still visible. Not only ControlNet is affected, most other extensions have this problem too.

### Version Platform Description

10:58:15-624628 INFO     Starting SD.Next
10:58:15-625625 INFO     Python 3.10.6 on Windows
10:58:15-739245 INFO     Version: app=sd.next updated=2023-10-22 hash=bbb37ccc
                         url=https://github.com/vladmandic/automatic.git/tree/master
10:58:16-112945 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
10:58:16-115935 DEBUG    Setting environment tuning
10:58:16-116931 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
10:58:16-117928 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
10:58:16-120918 INFO     nVidia CUDA toolkit detected: nvidia-smi present
10:58:16-204638 DEBUG    Repository update time: Mon Oct 23 05:52:30 2023
10:58:34-239830 INFO     Extensions enabled: ['clip-interrogator-ext', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'sd-extension-chainner',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'adetailer',
                         'multidiffusion-upscaler-for-automatic1111.7z', 'sd-webui-cd-tuner',
                         'sd-webui-lora-block-weight', 'sd-webui-openpose-editor', 'sd-webui-stablesr',
                         'sd-webui-vectorscope-cc', 'sd_webui_SAG', 'stable-diffusion-webui-anti-burn',
                         'ultimate-upscale-for-automatic1111']
10:58:37-908260 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
                         cross-optimization="Scaled-Dot-Product"
10:58:37-964133 INFO     Device: device=NVIDIA GeForce RTX 3090 n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8801
                         driver=545.84

### Relevant log output

```shell
Not sure what log would be needed here?
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.

**Comment by MrRedMinion** [comment]
I am still seeing the issue on "from image" tab. Where is the commit for this issue?

**Comment by vladmandic** [comment]
i think i found it - fixed in latest dev.

**Comment by vis223** [comment]
There is a similar issue on the models tab. I found it impossible to scroll to the left. I had to shrink the ui to 25% to see the download button. This was the hugging face link. It starts out okay but with usage becomes increasingly difficult to scroll left

**Comment by vladmandic** [comment]
> There is a similar issue on the models tab. I found it impossible to scroll to the left. I had to shrink the ui to 25% to see the download button. This was the hugging face link. It starts out okay but with usage becomes increasingly difficult to scroll left

Short comments like this are not something I can work on - please take 3min and create a new issue documenting everything fully so I can reproduce.

**Comment by vis223** [comment]
sure thing
________________________________
