### ISSUE TITLE
[Issue]: IMG2IMG not working: List index out of range

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#2656]
### Issue Description

I tried playing with the settings and disabling extensions but it still gives the error.
Example image generated in TXT2IMG: 
![00000-1793358884-best quality 1girl blonde light smile 1 0](https://github.com/vladmandic/automatic/assets/111918717/6c72a938-acb0-4561-9c84-486980459029)
I take it to IMG2IMG and it gives this error:

> 16:41:36-504873 ERROR    Exception: list index out of range
> 16:41:36-505874 ERROR    Arguments: args=('task(j2bs588hjqbryq1)', 0.0, 'best quality,\n1girl,\nblonde,\n(light smile:1.0), \n(school uniform:1.0),\n(full
>                          body:1.0),\nindoors, school', '', [], <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x1FB20332AD0>, None, None, None, None,
>                          None, None, 50, 16, 16, 4, 0, 1, True, False, False, 1, 1, 30, 4, 0.7, 5, 0, 2, 0.4, -1.0, -1.0, 0, 0, 0, 1, 1536, 1536, 1, 1,
>                          'RealESRGAN 4x+ Anime6B', 1, 256, 0, None, '', '', '', False, 4, 0.95, False, 1, 1, False, 0.6, 1, [], 0, '* `CFG Scale` should be
>                          2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p
>                          style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8,
>                          ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False,
>                          False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to
>                          set tile size</p>', 64, 0, 2, 0, '', [], 0, '', [], 0, '', [], False, True, False, False, False, False, 0, None, None, False, None,
>                          None, False, None, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size
>                          type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2, UiControlNetUnit(enabled=False, module='none',
>                          model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1,
>                          threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True),
>                          UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False,
>                          processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced',
>                          save_detected_map=True), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and
>                          Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False,
>                          control_mode='Balanced', save_detected_map=True), True, 6, 100, 'Half Cosine Up', 9, 'Half Cosine Up', 9, 2, True, 'MEAN', 'AD', 1,
>                          True, 0, 1, 0, 'Version 2', 1.3, 0.9, 0, 0.5, 0, 1, 1.4, 0.2, 0, 0.5, 0, 1, 1, 1, 0, 0.5, 0, 1) kwargs={}
> 16:41:36-543385 ERROR    gradio call: IndexError
> ┌─────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────┐
> │ E:\Programs\Stable Diffusion\automatic\modules\call_queue.py:31 in f                                                                                     │
> │                                                                                                                                                          │
> │   30 │   │   │   try:                                                                                                                                    │
> │ > 31 │   │   │   │   res = func(*args, **kwargs)                                                                                                         │
> │   32 │   │   │   │   progress.record_results(id_task, res)                                                                                               │
> │                                                                                                                                                          │
> │ E:\Programs\Stable Diffusion\automatic\modules\img2img.py:215 in img2img                                                                                 │
> │                                                                                                                                                          │
> │   214 │   │   seed_enable_extras=True,                                                                                                                   │
> │ > 215 │   │   sampler_name=sd_samplers.samplers_for_img2img[sampler_index].name,                                                                         │
> │   216 │   │   latent_sampler=sd_samplers.samplers[latent_index].name,                                                                                    │
> └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> IndexError: list index out of range

I tried it in safe mode, error is shorter but still present:

> 16:44:09-977064 ERROR    Exception: list index out of range
> 16:44:09-977064 ERROR    Arguments: args=('task(7pp5wja77kk97ho)', 0.0, 'best quality,\n1girl,\nblonde,\n(light smile:1.0),\n(school uniform:1.0),\n(full
>                          body:1.0),\nindoors, school', '', [], <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x249180A6E00>, None, None, None, None,
>                          None, None, 50, 16, 16, 4, 0, 1, True, False, False, 1, 1, 30, 4, 0.7, 5, 0, 2, 0.4, -1.0, -1.0, 0, 0, 0, 1, 1536, 1536, 1, 0,
>                          'None', 1, 256, 0, None, '', '', '', False, 4, 0.95, False, 1, 1, False, 0.6, 1, [], 0, '* `CFG Scale` should be 2 or lower.',
>                          True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings:
>                          Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4,
>                          0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will
>                          upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 0, '', [], 0, '', [],
>                          0, '', [], False, True, False, False, False, False, 0) kwargs={}
> 16:44:09-992693 ERROR    gradio call: IndexError
> ┌─────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────┐
> │ E:\Programs\Stable Diffusion\automatic\modules\call_queue.py:31 in f                                                                                     │
> │                                                                                                                                                          │
> │   30 │   │   │   try:                                                                                                                                    │
> │ > 31 │   │   │   │   res = func(*args, **kwargs)                                                                                                         │
> │   32 │   │   │   │   progress.record_results(id_task, res)                                                                                               │
> │                                                                                                                                                          │
> │ E:\Programs\Stable Diffusion\automatic\modules\img2img.py:215 in img2img                                                                                 │
> │                                                                                                                                                          │
> │   214 │   │   seed_enable_extras=True,                                                                                                                   │
> │ > 215 │   │   sampler_name=sd_samplers.samplers_for_img2img[sampler_index].name,                                                                         │
> │   216 │   │   latent_sampler=sd_samplers.samplers[latent_index].name,                                                                                    │
> └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> IndexError: list index out of range

### Version Platform Description

Version: app=sd.next updated=2023-12-19 hash=00281e15

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Should be fixed, update.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
I still have the error.
I think I updated? Under "System Info" it says 
app: SD.next
updated: 2023-12-29
hash: f4d4f8da

**Comment by vladmandic** [comment]
i said to upgrade because you noted your version as 2023-12-19 and latest is 12-29. if you're on 12-29 and still have the issue, please set `SD_PROCESS_DEBUG=true` environment variable and capture the log - i'll reopen once log is present.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
That's what the command window showed. I guess it shows the old version when it updates.
Both this and #2655 are on latest, everything was working before, I did some stuff hours ago and didn't have issues.
Anyway, I launched SD with the debug option, went straight to IMG2IMG and tried, errors:

> E:\Programs\Stable Diffusion\automatic>set SD_PROCESS_DEBUG=true
>
> E:\Programs\Stable Diffusion\automatic>.\webui.bat --debug
> Using VENV: E:\Programs\Stable Diffusion\automatic\venv
> 17:57:38-791213 INFO     Starting SD.Next
> 17:57:38-794770 INFO     Logger: file="E:\Programs\Stable Diffusion\automatic\sdnext.log" level=DEBUG size=65
>                          mode=create
> 17:57:38-796787 INFO     Python 3.10.11 on Windows
> 17:57:39-188122 INFO     Version: app=sd.next updated=2023-12-29 hash=f4d4f8da
>                          url=https://github.com/vladmandic/automatic/tree/master
> 17:57:39-934152 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
>                          system=Windows release=Windows-10-10.0.22621-SP0 python=3.10.11
> 17:57:39-937151 DEBUG    Setting environment tuning
> 17:57:39-938152 DEBUG    Cache folder: C:\Users\Yuri\.cache\huggingface\hub
> 17:57:39-939151 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
> 17:57:39-941661 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
> 17:57:39-943663 INFO     nVidia CUDA toolkit detected: nvidia-smi present
> 17:57:40-272528 DEBUG    Repository update time: Fri Dec 29 15:32:52 2023
> 17:57:40-273529 INFO     Startup: standard
> 17:57:40-274528 INFO     Verifying requirements
> 17:57:40-292804 INFO     Verifying packages
> 17:57:40-293988 INFO     Verifying submodules
> 17:57:42-780909 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
> 17:57:42-871240 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
> 17:57:42-967118 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
> 17:57:43-042370 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet / main
> 17:57:43-176257 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-images-browser / main
> 17:57:43-257433 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
> 17:57:43-338598 DEBUG    Submodule: modules/k-diffusion / master
> 17:57:43-435694 DEBUG    Submodule: modules/lora / main
> 17:57:43-516566 DEBUG    Submodule: wiki / master
> 17:57:43-568164 DEBUG    Register paths
> 17:57:43-644228 DEBUG    Installed packages: 221
> 17:57:43-645227 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
>                          'sd-webui-agent-scheduler', 'sd-webui-controlnet',
>                          'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
> 17:57:43-803450 DEBUG    Running extension installer: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\sd-extension-system-info\install.py
> 17:57:44-087304 DEBUG    Running extension installer: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
> 17:57:44-355632 DEBUG    Running extension installer: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\sd-webui-controlnet\install.py
> 17:57:44-631400 DEBUG    Running extension installer: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
> 17:57:44-908141 DEBUG    Running extension installer: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
> 17:57:45-179420 DEBUG    Extensions all: ['a1111-sd-webui-tagcomplete', 'sd-dynamic-thresholding',
>                          'sd-webui-freeu', 'sd-webui-supermerger', 'sdweb-merge-block-weighted-gui',
>                          'stable-diffusion-webui-model-toolkit', 'stable-diffusion-webui-state',
>                          'ultimate-upscale-for-automatic1111']
> 17:57:45-419674 DEBUG    Running extension installer: E:\Programs\Stable
>                          Diffusion\automatic\extensions\sd-webui-supermerger\install.py
> 17:57:49-053861 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
>                          'sd-webui-agent-scheduler', 'sd-webui-controlnet',
>                          'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg',
>                          'a1111-sd-webui-tagcomplete', 'sd-dynamic-thresholding', 'sd-webui-freeu',
>                          'sd-webui-supermerger', 'sdweb-merge-block-weighted-gui',
>                          'stable-diffusion-webui-model-toolkit', 'stable-diffusion-webui-state',
>                          'ultimate-upscale-for-automatic1111']
> 17:57:49-058861 INFO     Verifying requirements
> 17:57:49-067367 DEBUG    Setup complete without errors: 1703869069
> 17:57:49-084884 INFO     Extension preload: {'extensions-builtin': 0.01, 'extensions': 0.0}
> 17:57:49-086885 DEBUG    Starting module: <module 'webui' from 'E:\\Programs\\Stable
>                          Diffusion\\automatic\\webui.py'>
> 17:57:49-088884 INFO     Command line args: ['--debug'] debug=True
> 17:57:49-090387 DEBUG    Env flags: ['SD_PROCESS_DEBUG=true']
> 17:58:05-264661 INFO     Load packages: torch=2.1.0+cu121 diffusers=0.25.0 gradio=3.43.2
> 17:58:07-997944 DEBUG    Read: file="config.json" json=27 bytes=1755 time=0.000
> 17:58:07-999944 DEBUG    Unknown settings: ['state_txt2img', 'state_img2img']
> 17:58:08-001446 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
>                          cross-optimization="Scaled-Dot-Product"
> 17:58:08-093240 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801
>                          driver=546.33
> 17:58:18-192063 TRACE    Trace: PROCESS
> 17:58:19-295099 TRACE    Trace: PROCESS
> 17:58:19-302607 TRACE    Trace: PROCESS
> 17:58:19-313119 DEBUG    Entering start sequence
> 17:58:19-315121 DEBUG    Initializing
> 17:58:19-317121 INFO     Available VAEs: path="models\VAE" items=3
> 17:58:19-320119 INFO     Disabled extensions: []
> 17:58:19-333879 DEBUG    Read: file="cache.json" json=2 bytes=11462 time=0.004
> 17:58:19-879553 DEBUG    Read: file="metadata.json" json=521 bytes=93709927 time=0.544
> 17:58:19-883587 INFO     Available models: path="models\Stable-diffusion" items=18 time=0.56
> 17:58:20-625537 DEBUG    Load extensions
> 17:58:21-170008 INFO     Extension: script='scripts\faceid.py' 17:58:21-169009 ERROR
>                           FaceID: No module named 'insightface'
> 17:58:22-795705 INFO     Extension:
>                          script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
>                          sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
> 17:58:23-248506 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\api.py' ControlNet
>                          preprocessor location: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
> 17:58:23-616268 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py'
>                          Warning: ControlNet failed to load SGM - will use LDM instead.
> 17:58:23-623775 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\hook.py' Warning:
>                          ControlNet failed to load SGM - will use LDM instead.
> 17:58:27-162672 INFO     Extension:
>                          script='extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py' Tag
>                          Autocomplete: Could not locate model-keyword extension, Lora trigger word completion
>                          will be limited to those added through the extra networks menu.
> 17:58:27-206199 INFO     Extension: script='extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py'
>                          ======
> 17:58:27-207199 INFO     Extension: script='extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py'
>                          Warning! Using legacy KDiff version! Is your WebUI up to date?
> 17:58:27-209199 INFO     Extension: script='extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py'
>                          ======
> 17:58:27-253727 INFO     Extension: script='extensions\sd-webui-freeu\scripts\freeu.py' [sd-webui-freeu]
>                          Controlnet support: *enabled*
> 17:58:27-880595 INFO     Extensions time: 7.25 { automatic=0.59 Lora=0.85 sd-extension-chainner=0.16
>                          sd-webui-agent-scheduler=0.54 sd-webui-controlnet=0.84
>                          stable-diffusion-webui-images-browser=0.51 stable-diffusion-webui-rembg=2.93
>                          a1111-sd-webui-tagcomplete=0.09 sd-webui-supermerger=0.34
>                          sdweb-merge-block-weighted-gui=0.07 stable-diffusion-webui-model-toolkit=0.19 }
> 17:58:27-963654 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.014
> 17:58:27-982672 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719
>                          time=0.017
> 17:58:27-985670 DEBUG    chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
> 17:58:27-987672 DEBUG    Upscaler type=ESRGAN folder="models\ESRGAN" model="2x_Futsuu_Anime_Compact_130k_net_g"
>                          path="models\ESRGAN\2x_Futsuu_Anime_Compact_130k_net_g.pth"
> 17:58:27-989670 DEBUG    Upscaler type=ESRGAN folder="models\ESRGAN" model="4x-AnimeSharp"
>                          path="models\ESRGAN\4x-AnimeSharp.pth"
> 17:58:27-992178 DEBUG    Upscaler type=ESRGAN folder="models\ESRGAN" model="4xESRGAN"
>                          path="models\ESRGAN\4xESRGAN.pth"
> 17:58:27-994182 DEBUG    Upscaler type=ESRGAN folder="models\ESRGAN" model="BSRGAN"
>                          path="models\ESRGAN\BSRGAN.pth"
> 17:58:27-997686 DEBUG    Load upscalers: total=54 downloaded=5 user=4 time=0.11 ['None', 'Lanczos', 'Nearest',
>                          'ChaiNNer', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
> 17:58:28-026223 DEBUG    Load styles: folder="models\styles" items=288 time=0.02
> 17:58:28-069827 DEBUG    Creating UI
> 17:58:28-071331 INFO     Load UI theme: name="black-teal" style=Auto base=sdnext.css
> 17:58:28-530342 DEBUG    Extra networks: page='lora' items=495 subfolders=23 tab=txt2img
>                          folders=['models\\Lora', 'models\\LyCORIS'] list=0.41 desc=0.10 info=0.06 workers=2
> 17:58:28-543356 DEBUG    Extra networks: page='style' items=288 subfolders=2 tab=txt2img
>                          folders=['models\\styles', 'html'] list=0.01 desc=0.00 info=0.00 workers=2
> 17:58:28-547356 DEBUG    Extra networks: page='embedding' items=0 subfolders=1 tab=txt2img
>                          folders=['models\\embeddings'] list=0.00 desc=0.00 info=0.00 workers=2
> 17:58:28-550355 DEBUG    Extra networks: page='hypernetwork' items=0 subfolders=1 tab=txt2img
>                          folders=['models\\hypernetworks'] list=0.00 desc=0.00 info=0.00 workers=2
> 17:58:28-812399 DEBUG    Read: file="ui-config.json" json=66 bytes=4297 time=0.008
> 17:58:30-449978 DEBUG    Themes: builtin=9 default=5 external=55
> 17:58:30-728854 DEBUG    Script: 0.2 ui_tabs E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\im
>                          age_browser.py
> 17:58:30-844226 DEBUG    Read: file="E:\Programs\Stable Diffusion\automatic\html\extensions.json" json=335
>                          bytes=197085 time=0.005
> 17:58:32-123468 DEBUG    Extension list: processed=320 installed=15 enabled=15 disabled=0 visible=320 hidden=0
> 17:58:32-733200 INFO     Local URL: http://127.0.0.1:7860/
> 17:58:32-734200 DEBUG    Gradio functions: registered=2392
> 17:58:32-735199 INFO     Initializing middleware
> 17:58:32-746709 DEBUG    Creating API
> 17:58:32-811779 DEBUG    SD-System-Info: benchmark data loaded: E:\Programs\Stable
>                          Diffusion\automatic\extensions-builtin\sd-extension-system-info\scripts\benchmark-data-
>                          local.json
> 17:58:32-891726 INFO     [AgentScheduler] Task queue is empty
> 17:58:32-892731 INFO     [AgentScheduler] Registering APIs
> 17:58:33-027806 DEBUG    Scripts setup: ['Prompt Matrix:0.006', 'ControlNet:0.04', 'FreeU:0.014']
> 17:58:33-029805 DEBUG    Model metadata: file="metadata.json" no changes
> 17:58:33-030805 DEBUG    Model auto load disabled
> 17:58:33-032309 DEBUG    Save: file="config.json" json=27 bytes=1688 time=0.000
> 17:58:33-034313 INFO     Startup time: 43.93 { torch=12.34 gradio=3.70 diffusers=0.13 libraries=14.05
>                          extensions=7.25 models=0.56 face-restore=0.74 upscalers=0.12 extra-networks=0.07
>                          ui-extra-networks=0.48 ui-txt2img=0.06 ui-img2img=0.06 ui-interrogate=0.07
>                          ui-settings=1.72 ui-extensions=1.62 ui-defaults=0.29 launch=0.33 api=0.05
>                          app-started=0.23 }
> 17:59:47-600575 INFO     MOTD: N/A
> 17:59:52-074380 DEBUG    Themes: builtin=9 default=5 external=55
> 17:59:55-448699 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64;
>                          x64; rv:121.0) Gecko/20100101 Firefox/121.0
> 17:59:59-835285 DEBUG    Server: alive=True jobs=0 requests=56 uptime=112 memory=1.31/31.12
>                          backend=Backend.ORIGINAL state=idle
> 18:00:35-280351 DEBUG    Model requested: fn=img2img
> 18:00:35-282352 INFO     Select: model="BreakDomainI2428 [8f2b009d0f]"
> 18:00:35-284354 DEBUG    Load model weights: existing=False target=E:\Programs\Stable
>                          Diffusion\automatic\models\Stable-diffusion\BreakDomainI2428.safetensors info=None
> Loading model: E:\Programs\Stable Diffusion\automatic\models\Stable-diffusion\BreakDomainI2428.safetensors -  -…
> 18:00:37-777378 DEBUG    Load model: name=E:\Programs\Stable
>                          Diffusion\automatic\models\Stable-diffusion\BreakDomainI2428.safetensors dict=True
> 18:00:38-224382 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
> 18:00:38-226394 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16
>                          unet=torch.float16 context=no_grad fp16=True bf16=False
> 18:00:38-229393 DEBUG    Model dict loaded: {'ram': {'used': 1.34, 'total': 31.12}, 'gpu': {'used': 1.58,
>                          'total': 23.99}, 'retries': 0, 'oom': 0}
> 18:00:38-253139 DEBUG    Model config loaded: {'ram': {'used': 1.34, 'total': 31.12}, 'gpu': {'used': 1.58,
>                          'total': 23.99}, 'retries': 0, 'oom': 0}
> 18:00:44-734969 INFO     LDM: LatentDiffusion: mode=eps
> 18:00:44-736480 INFO     LDM: DiffusionWrapper params=859.52M
> 18:00:44-737479 DEBUG    Model created from config: E:\Programs\Stable
>                          Diffusion\automatic\configs\v1-inference.yaml
> 18:00:44-738478 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
>                          file="E:\Programs\Stable
>                          Diffusion\automatic\models\Stable-diffusion\BreakDomainI2428.safetensors" size=2309MB
> 18:00:44-741478 DEBUG    Model weights loading: {'ram': {'used': 5.35, 'total': 31.12}, 'gpu': {'used': 1.58,
>                          'total': 23.99}, 'retries': 0, 'oom': 0}
> Loading model: models\VAE\vae-ft-mse-840000-ema-pruned.safetensors ------------------------ 0.0/334.6 MB -:--:--
> 18:01:07-506548 DEBUG    Model weights loaded: {'ram': {'used': 7.61, 'total': 31.12}, 'gpu': {'used': 1.58,
>                          'total': 23.99}, 'retries': 0, 'oom': 0}
> 18:01:08-021494 DEBUG    Model weights moved: {'ram': {'used': 6.04, 'total': 31.12}, 'gpu': {'used': 3.61,
>                          'total': 23.99}, 'retries': 0, 'oom': 0}
> 18:01:08-029002 INFO     Cross-attention: optimization=Scaled-Dot-Product options=[]
> 18:01:08-479239 INFO     Load embeddings: loaded=1 skipped=0 time=0.45
> 18:01:08-484239 INFO     Model loaded in 33.20 { load=2.49 config=0.48 create=6.49 apply=19.25 vae=3.51
>                          move=0.51 embeddings=0.45 }
> 18:01:08-787879 DEBUG    gc: collected=966 device=cuda {'ram': {'used': 6.11, 'total': 31.12}, 'gpu': {'used':
>                          3.61, 'total': 23.99}, 'retries': 0, 'oom': 0}
> 18:01:08-791879 INFO     Model load finished: {'ram': {'used': 6.11, 'total': 31.12}, 'gpu': {'used': 3.61,
>                          'total': 23.99}, 'retries': 0, 'oom': 0} cached=0
> 18:01:08-927995 TRACE    img2img: id_task=task(otqzssqhbsb2tyf)|mode=0.0|prompt=best quality,
>                          1girl,
>                          blonde,
>                          (light smile:1.0),
>                          (school uniform:1.0),
>                          (full body:1.0),
>                          indoors, school|negative_prompt=(3d, realistic:1.4), (steam, smoke:1.4),
>                          (fingernails:1.2), (nipples, areolae, areola
>                          slip:1.0)|prompt_styles=[]|init_img=<PIL.Image.Image image mode=RGBA size=1024x1536 at
>                          0x1FC2014B130>|sketch=None|init_img_with_mask=None|inpaint_color_sketch=None|inpaint_co
>                          lor_sketch_orig=None|init_img_inpaint=None|init_mask_inpaint=None|steps=50|sampler_inde
>                          x=16|latent_index=16|mask_blur=4|mask_alpha=0|inpainting_fill=1|full_quality=True|resto
>                          re_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=30|image_cfg_scale=4|clip_s
>                          kip=2|denoising_strength=0.4|seed=-1.0|subseed-1.0|subseed_strength=0|seed_resize_from_
>                          h=0|seed_resize_from_w=0|selected_scale_tab=0|height=1536|width=1536|scale_by=1|resize_
>                          mode=0|resize_name=None|inpaint_full_res=1|inpaint_full_res_padding=256|inpainting_mask
>                          _invert=0|img2img_batch_files=None|img2img_batch_input_dir=|img2img_batch_output_dir=|i
>                          mg2img_batch_inpaint_mask_dir=|override_settings_texts=[]
> 18:01:08-948528 ERROR    Exception: list index out of range
> 18:01:08-950528 ERROR    Arguments: args=('task(otqzssqhbsb2tyf)', 0.0, 'best quality,\n1girl,\nblonde,\n(light
>                          smile:1.0), \n(school uniform:1.0),\n(full body:1.0),\nindoors, school', '(3d,
>                          realistic:1.4), (steam, smoke:1.4), (fingernails:1.2), (nipples, areolae, areola
>                          slip:1.0)', [], <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x1FC2014B130>,
>                          None, None, None, None, None, None, 50, 16, 16, 4, 0, 1, True, False, False, 1, 1, 30,
>                          4, 0.7, 5, 0, 2, 0.4, -1.0, -1.0, 0, 0, 0, 0, 1536, 1536, 1, 0, 'None', 1, 256, 0,
>                          None, '', '', '', False, 4, 0.95, False, 1, 1, False, 0.6, 1, [], 0, '* `CFG Scale`
>                          should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5,
>                          'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling
>                          Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left',
>                          'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False,
>                          False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will
>                          upscale the image by the selected scale factor; use width and height sliders to set
>                          tile size</p>', 64, 0, 2, 0, '', [], 0, '', [], 0, '', [], False, True, False, False,
>                          False, False, 0, None, None, False, None, None, False, None, None, False, 50, '<p
>                          style="margin-bottom:0.75em">Will upscale the image depending on the selected target
>                          size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2,
>                          UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None,
>                          resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1,
>                          threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False,
>                          control_mode='Balanced', save_detected_map=True), UiControlNetUnit(enabled=False,
>                          module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize',
>                          low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0,
>                          guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True),
>                          UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None,
>                          resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1,
>                          threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False,
>                          control_mode='Balanced', save_detected_map=True), True, 6, 100, 'Half Cosine Up', 9,
>                          'Half Cosine Up', 9, 2, True, 'MEAN', 'AD', 1, True, 0, 1, 0, 'Version 2', 1.3, 0.9, 0,
>                          0.5, 0, 1, 1.4, 0.2, 0, 0.5, 0, 1, 1, 1, 0, 0.5, 0, 1) kwargs={}
> 18:01:08-991089 ERROR    gradio call: IndexError
> ┌───────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────┐
> │ E:\Programs\Stable Diffusion\automatic\modules\call_queue.py:31 in f                                         │
> │                                                                                                              │
> │   30 │   │   │   try:                                                                                        │
> │ > 31 │   │   │   │   res = func(*args, **kwargs)                                                             │
> │   32 │   │   │   │   progress.record_results(id_task, res)                                                   │
> │                                                                                                              │
> │ E:\Programs\Stable Diffusion\automatic\modules\img2img.py:215 in img2img                                     │
> │                                                                                                              │
> │   214 │   │   seed_enable_extras=True,                                                                       │
> │ > 215 │   │   sampler_name=sd_samplers.samplers_for_img2img[sampler_index].name,                             │
> │   216 │   │   latent_sampler=sd_samplers.samplers[latent_index].name,                                        │
> └──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> IndexError: list index out of range

**Comment by vladmandic** [comment]
this is basically saying that sampler with a selected index does not exist.
i'll handle it.

**Comment by vladmandic** [comment]
ok, this time this is fixed for real and included in dev branch, i plan to merge to master soon as a fix-only release.
