### ISSUE TITLE
[Issue]: Train Tab is blank

### ISSUE THREAD

**Issue by firedelta4** [vladmandic/automatic#2715]
### Issue Description

Since 2 or 3 days the Train tab is just blank.
I checked with dev tools and didn't see any console errors for the page or anything really.
It's also not just hidden from what I saw it's just not rendered to the DOM at all.

![brave_8TLGAu0Tuj](https://github.com/vladmandic/automatic/assets/156543773/b32a45df-6bff-44c9-afb2-2d0cc038275f)

### Version Platform Description

20:48:34-752266 INFO     Starting SD.Next
20:48:34-757271 INFO     Python 3.11.7 on Windows
20:48:34-865861 INFO     Version: app=sd.next updated=2024-01-13 hash=e395f310 url=https://github.com/vladmandic/automatic//tree/dev
20:48:36-205942 INFO     Latest published version: 5fb290f443d5f38a5c9f6e6095aabeab8e3a991d 2024-01-13T13:47:29Z
20:48:36-213460 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows release=Windows-10-10.0.22631-SP0 python=3.11.7
20:48:36-215040 DEBUG    Setting environment tuning
20:48:36-217043 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
20:48:36-217043 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
20:48:36-219558 INFO     nVidia CUDA toolkit detected: nvidia-smi present
20:48:43-729526 DEBUG    Extensions all: ['--sd-webui-ar-plus', 'adetailer', 'canvas-zoom', 'latent-upscale', 'sd-dynamic-thresholding', 'sd-webui-color-enhance', 'sd-webui-infinite-image-browsing', 'sd-webui-reactor', 'sd-webui-resharpen', 'ultimate-upscale-for-automatic1111']
20:49:48-703093 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', '--sd-webui-ar-plus', 'adetailer', 'canvas-zoom', 'latent-upscale',  'sd-dynamic-thresholding', 'sd-webui-color-enhance', 'sd-webui-infinite-image-browsing', 'sd-webui-reactor', 'sd-webui-resharpen', 'ultimate-upscale-for-automatic1111']
20:55:33-527577 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
20:55:33-577998 INFO     Device: device=NVIDIA GeForce RTX 4060 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801 driver=546.33

### Backend

Diffusers

### Branch

dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev.

**Comment by firedelta4** [comment]
This is only half fixed for me.
I am still missing the sub tab to actually train an embedding or hypernetwork unless that sub tab is expected to be hidden when using the diffusers backend.
Currently it only shows "Preview Settings" and "Preprocess Images"

![sbwNQK1IS6](https://github.com/vladmandic/automatic/assets/156543773/173efdd2-2a2a-4271-bee9-44d393bb399b)

**Comment by vladmandic** [comment]
> unless that sub tab is expected to be hidden when using the diffusers backend.

correct - ti and hn training are based on original backend.
new training for diffusers is planned.
