### ISSUE TITLE
[Issue]: lora panel disappeard

### ISSUE THREAD

**Issue by zhucezy** [vladmandic/automatic#3545]
### Issue Description

I'm not sure what is changed but lora panel disappeard. And "Avalible lora" is not in log to. 

### Version Platform Description

23:06:42-434736 INFO     Starting SD.Next
23:06:42-434736 INFO     Logger: file="D:\sd-next\sdnext.log" level=DEBUG size=65 mode=create
23:06:42-448781 INFO     Python version=3.10.6 platform=Windows bin="D:\sd-next\venv\Scripts\python.exe"
                         venv="D:\sd-next\venv"
23:06:42-618443 INFO     Version: app=sd.next updated=2024-10-17 hash=5c684cb0 branch=master
                         url=https://gitee.com/ranxv/sd-next/tree/master ui=main
23:06:43-029195 ERROR    Failed to check version: 'commit' {'message': "API rate limit exceeded for 153.254.103.230.
                         (But here's the good news: Authenticated requests get a higher rate limit. Check out the
                         documentation for more details.)", 'documentation_url':
                         'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
23:06:43-045025 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.6

### Relevant log output

```shell
formal log
20:25:41-268919 INFO     Load embeddings: loaded=0 skipped=0 time=0.00
20:25:41-658410 INFO     Load model: time=10.97 load=10.94 native=512 {'ram': {'used': 8.23, 'total': 14.76}}
20:25:41-727349 INFO     Base: class=StableDiffusionPipeline
Progress 17.95s/it █████                               15% 3/20 00:59 05:05 Base20:26:44-763891 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.00
20:26:44-824346 INFO     LoRA networks: available=2 folders=2
20:26:44-937913 INFO     Available VAEs: path="models\VAE" items=0

Now:
23:06:56-236938 DEBUG    Initializing
23:06:56-284272 INFO     Available VAEs: path="models\VAE" items=0
23:06:56-284272 DEBUG    Available UNets: path="models\UNET" items=0
23:06:56-284272 DEBUG    Available T5s: path="models\T5" items=0
23:06:56-284272 INFO     Disabled extensions: ['sdnext-modernui']
23:06:56-284272 DEBUG    Read: file="cache.json" json=2 bytes=493 time=0.000
23:06:56-284272 DEBUG    Read: file="metadata.json" json=4 bytes=7905 time=0.000
23:06:56-300056 DEBUG    Scanning diffusers cache: folder=models\Diffusers items=0 time=0.00
23:06:56-300056 INFO     Available models: path="models\Stable-diffusion" items=2 time=0.02
23:06:56-380136 DEBUG    Load extensions
23:06:56-472571 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m23:06:56-456814[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m1[0m
                         [33mfolders[0m=[1;36m2[0m
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
that may be the case, but think what information would someone need?
- what is your lora folder?
- whats inside that lora folder

regarding logging, that's been fixed, try to upgrade and post full log.

**Comment by zhucezy** [comment]
I just put a lora file into the default path as models\lora. The lora was worked well in webui. Please check the full log.
[sdnext.log](https://github.com/user-attachments/files/17602029/sdnext.log)

**Comment by vladmandic** [comment]
i said logging has been fixed and try to upgrade - this log is still with old version.

from the log, 1 lora is found: 
> ui_extra_networks | Networks: page='lora' items=1 subfolders=0

so if something is missing, show what is missing - at least a screenshot?

**Comment by zhucezy** [comment]
I updated it and lora availebled but still can't be found in main page.
It can be found in "Models & networks" after checked "system info".
In Extensions page, lora status is a blue O, something strange?
[sdnext.log](https://github.com/user-attachments/files/17605462/sdnext.log)
![Clipboard02](https://github.com/user-attachments/assets/3e338572-f1c0-4084-bbb5-16bfcfb4d544)
![Clipboard04](https://github.com/user-attachments/assets/041a526b-4c85-44b7-9003-b731ca58855b)
![Clipboard05](https://github.com/user-attachments/assets/92799792-30b4-416c-ae8e-5a3e6e0fea19)
![Clipboard03](https://github.com/user-attachments/assets/352ad961-9f25-4c7f-b32e-2439433d865b)

**Comment by vladmandic** [comment]
are you talking about networks panel with list of loras?
top right of the main screen -> click on networks!

**Comment by zhucezy** [comment]
yeah, it works! Thanks a lot!
