### ISSUE TITLE
[Issue]: Failed to load ZLUDA: Could not find module 'nvrtc64_112_0.dll'

### ISSUE THREAD

**Issue by L00PED345** [vladmandic/automatic#3646]
### Issue Description

I followed all the steps in the guide, but when I open the .bat, this error appears in the cmd, the web-ui opens normally. 
![issue](https://github.com/user-attachments/assets/b2e2104c-d97b-4e64-b610-9791d01c8d8b)
![folder](https://github.com/user-attachments/assets/a40cd663-bad8-4d26-8379-4200772be463)

### Version Platform Description

Windows 10 AMD RX 6600

### Relevant log output

```shell
2024-12-22 04:08:18,543 | sd | INFO | launch | Starting SD.Next
2024-12-22 04:08:18,547 | sd | INFO | installer | Logger: file="E:\automatic\sdnext.log" level=DEBUG size=65 mode=create
2024-12-22 04:08:18,549 | sd | INFO | installer | Python: version=3.10.6 platform=Windows bin="E:\automatic\venv\Scripts\python.exe" venv="E:\automatic\venv"
2024-12-22 04:08:18,743 | sd | INFO | installer | Version: app=sd.next updated=2024-12-09 hash=a2f5a39a branch=master url=https://github.com/vladmandic/automatic/tree/master ui=main
2024-12-22 04:08:19,096 | sd | INFO | launch | Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.6 docker=False
2024-12-22 04:08:19,099 | sd | DEBUG | installer | Packages: venv=venv site=['venv', 'venv\\lib\\site-packages']
2024-12-22 04:08:19,103 | sd | INFO | launch | Args: ['--use-zluda', '--debug', '--autolaunch']
2024-12-22 04:08:19,105 | sd | DEBUG | installer | Setting environment tuning
2024-12-22 04:08:19,106 | sd | DEBUG | installer | Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
2024-12-22 04:08:19,114 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
2024-12-22 04:08:19,128 | sd | INFO | installer | Python: version=3.10.6 platform=Windows bin="E:\automatic\venv\Scripts\python.exe" venv="E:\automatic\venv"
2024-12-22 04:08:19,133 | sd | INFO | installer | ROCm: AMD toolkit detected
2024-12-22 04:08:19,608 | sd | INFO | installer | ROCm: agents=['gfx1032']
2024-12-22 04:08:19,610 | sd | INFO | installer | ROCm: version=6.2, using agent gfx1032
2024-12-22 04:08:19,653 | sd | WARNING | installer | Failed to load ZLUDA: Could not find module 'E:\automatic\.zluda\nvrtc64_112_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
2024-12-22 04:08:19,655 | sd | INFO | installer | Using CPU-only torch
2024-12-22 04:08:19,865 | sd | INFO | installer | Install: verifying requirements
2024-12-22 04:08:19,870 | sd | INFO | installer | Verifying packages
2024-12-22 04:08:19,921 | sd | DEBUG | installer | Timestamp repository update time: Mon Dec  9 09:27:14 2024
2024-12-22 04:08:19,923 | sd | INFO | launch | Startup: standard
2024-12-22 04:08:19,924 | sd | INFO | installer | Verifying submodules
2024-12-22 04:08:22,419 | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-extension-chainner / main
2024-12-22 04:08:22,550 | sd | DEBUG | installer | Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
2024-12-22 04:08:22,552 | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-extension-system-info / main
2024-12-22 04:08:22,638 | sd | DEBUG | installer | Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
2024-12-22 04:08:22,767 | sd | DEBUG | installer | Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
2024-12-22 04:08:22,769 | sd | DEBUG | installer | Git submodule: extensions-builtin/sdnext-modernui / main
2024-12-22 04:08:22,858 | sd | DEBUG | installer | Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
2024-12-22 04:08:22,949 | sd | DEBUG | installer | Git submodule: modules/k-diffusion / master
2024-12-22 04:08:23,075 | sd | DEBUG | installer | Git detached head detected: folder="wiki" reattach=master
2024-12-22 04:08:23,077 | sd | DEBUG | installer | Git submodule: wiki / master
2024-12-22 04:08:23,147 | sd | DEBUG | paths | Register paths
2024-12-22 04:08:23,262 | sd | DEBUG | installer | Installed packages: 179
2024-12-22 04:08:23,265 | sd | DEBUG | installer | Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
2024-12-22 04:08:23,594 | sd | DEBUG | installer | Extension installer: E:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
2024-12-22 04:08:26,267 | sd | DEBUG | installer | Extension installer: E:\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
2024-12-22 04:08:33,526 | sd | DEBUG | installer | Extensions all: []
2024-12-22 04:08:33,530 | sd | INFO | installer | Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
2024-12-22 04:08:33,532 | sd | INFO | installer | Install: verifying requirements
2024-12-22 04:08:33,533 | sd | DEBUG | launch | Setup complete without errors: 1734836914
2024-12-22 04:08:33,539 | sd | DEBUG | installer | Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
2024-12-22 04:08:33,541 | sd | INFO | launch | Command line args: ['--use-zluda', '--debug', '--autolaunch'] autolaunch=True use_zluda=True debug=True
2024-12-22 04:08:33,543 | sd | DEBUG | launch | Env flags: []
2024-12-22 04:08:33,545 | sd | DEBUG | launch | Starting module: <module 'webui' from 'E:\\automatic\\webui.py'>
2024-12-22 04:08:40,083 | sd | INFO | loader | Torch: torch==2.5.1+cpu torchvision==0.20.1+cpu
2024-12-22 04:08:40,088 | sd | INFO | loader | Packages: diffusers==0.32.0.dev0 transformers==4.46.2 accelerate==1.1.1 gradio==3.43.2
2024-12-22 04:08:40,760 | sd | DEBUG | shared | Huggingface cache: folder="C:\Users\Stanislav\.cache\huggingface\hub"
2024-12-22 04:08:40,777 | sd | DEBUG | shared | Read: file="config.json" json=31 bytes=1338 time=0.000
2024-12-22 04:08:40,980 | sd | INFO | shared | Engine: backend=Backend.DIFFUSERS compute=cpu device=cpu attention="Scaled-Dot-Product" mode=no_grad
2024-12-22 04:08:40,983 | sd | DEBUG | shared | Read: file="html\reference.json" json=59 bytes=31585 time=0.000
2024-12-22 04:08:40,986 | sd | INFO | devices | Torch parameters: backend=cpu device=cpu config=Auto dtype=torch.bfloat16 vae=torch.bfloat16 unet=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upscast=False deterministic=False test-fp16=True test-bf16=True optimization="Scaled-Dot-Product"
2024-12-22 04:08:41,161 | sd | DEBUG | __init__ | ONNX: version=1.20.1 provider=CPUExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
2024-12-22 04:08:41,226 | sd | INFO | shared | Device: 
2024-12-22 04:08:41,318 | sd | DEBUG | sd_hijack | Importing LDM
2024-12-22 04:08:41,332 | sd | DEBUG | webui | Entering start sequence
2024-12-22 04:08:41,336 | sd | DEBUG | webui | Initializing
2024-12-22 04:08:41,375 | sd | INFO | sd_vae | Available VAEs: path="models\VAE" items=0
2024-12-22 04:08:41,378 | sd | INFO | sd_unet | Available UNets: path="models\UNET" items=0
2024-12-22 04:08:41,381 | sd | INFO | model_te | Available TEs: path="models\Text-encoder" items=0
2024-12-22 04:08:41,383 | sd | INFO | extensions | Disabled extensions: ['sdnext-modernui']
2024-12-22 04:08:41,386 | sd | DEBUG | modelloader | Scanning diffusers cache: folder="models\Diffusers" items=0 time=0.00
2024-12-22 04:08:41,388 | sd | INFO | sd_checkpoint | Available Models: path="models\Stable-diffusion" items=0 time=0.00
2024-12-22 04:08:41,479 | sd | INFO | yolo | Available Yolo: path="models\yolo" items=6 downloaded=0
2024-12-22 04:08:41,483 | sd | INFO | webui | Load extensions
2024-12-22 04:08:41,761 | sd | INFO | networks | Available LoRAs: path="models\Lora" items=0 folders=2 time=0.00
2024-12-22 04:08:42,389 | sd | INFO | script_loading | Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
2024-12-22 04:08:42,397 | sd | DEBUG | webui | Extensions init time: 0.91 pulid_ext.py=0.19 Lora=0.20 sd-webui-agent-scheduler=0.39
2024-12-22 04:08:42,420 | sd | DEBUG | shared | Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000
2024-12-22 04:08:42,423 | sd | DEBUG | shared | Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719 time=0.000
2024-12-22 04:08:42,428 | sd | DEBUG | chainner_model | chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
2024-12-22 04:08:42,435 | sd | INFO | modelloader | Available Upscalers: items=53 downloaded=0 user=0 time=0.04 types=['None', 'Lanczos', 'Nearest', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
2024-12-22 04:08:42,465 | sd | INFO | styles | Available Styles: folder="models\styles" items=288 time=0.03
2024-12-22 04:08:42,472 | sd | INFO | webui | UI start
2024-12-22 04:08:42,473 | sd | DEBUG | theme | UI themes available: type=Standard themes=12
2024-12-22 04:08:42,475 | sd | INFO | theme | UI theme: type=Standard name="black-teal"
2024-12-22 04:08:42,489 | sd | DEBUG | ui_javascript | UI theme: css="E:\automatic\javascript\black-teal.css" base="sdnext.css" user="None"
2024-12-22 04:08:42,493 | sd | DEBUG | ui_txt2img | UI initialize: txt2img
2024-12-22 04:08:42,539 | sd | DEBUG | ui_extra_networks | Networks: page='model' items=58 subfolders=2 tab=txt2img folders=['models\\Stable-diffusion', 'models\\Diffusers', 'models\\Reference'] list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-12-22 04:08:42,545 | sd | DEBUG | ui_extra_networks | Networks: page='lora' items=0 subfolders=0 tab=txt2img folders=['models\\Lora', 'models\\LyCORIS'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-12-22 04:08:42,558 | sd | DEBUG | ui_extra_networks | Networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles', 'html'] list=0.03 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-12-22 04:08:42,564 | sd | DEBUG | ui_extra_networks | Networks: page='embedding' items=0 subfolders=0 tab=txt2img folders=['models\\embeddings'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-12-22 04:08:42,569 | sd | DEBUG | ui_extra_networks | Networks: page='vae' items=0 subfolders=0 tab=txt2img folders=['models\\VAE'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-12-22 04:08:42,574 | sd | DEBUG | ui_extra_networks | Networks: page='history' items=0 subfolders=0 tab=txt2img folders=[] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
2024-12-22 04:08:42,812 | sd | DEBUG | ui_img2img | UI initialize: img2img
2024-12-22 04:08:42,971 | sd | DEBUG | ui_control_helpers | UI initialize: control models=models\control
2024-12-22 04:08:43,385 | sd | DEBUG | shared | Read: file="ui-config.json" json=0 bytes=2 time=0.000
2024-12-22 04:08:43,549 | sd | DEBUG | theme | UI themes available: type=Standard themes=12
2024-12-22 04:08:43,935 | sd | DEBUG | shared | Reading failed: E:\automatic\html\extensions.json [Errno 2] No such file or directory: 'E:\\automatic\\html\\extensions.json'
2024-12-22 04:08:43,995 | sd | INFO | ui_extensions | Extension list is empty: refresh required
2024-12-22 04:08:44,687 | sd | DEBUG | ui_extensions | Extension list: processed=6 installed=6 enabled=5 disabled=1 visible=6 hidden=0
2024-12-22 04:08:44,834 | sd | DEBUG | webui | Root paths: ['E:\\automatic']
2024-12-22 04:08:44,931 | sd | INFO | webui | Local URL: http://127.0.0.1:7860/
2024-12-22 04:08:44,933 | sd | DEBUG | webui | Gradio functions: registered=1862
2024-12-22 04:08:44,935 | sd | DEBUG | middleware | API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class 'starlette.middleware.gzip.GZipMiddleware'>]
2024-12-22 04:08:44,940 | sd | DEBUG | webui | API initialize
2024-12-22 04:08:45,124 | sd | INFO | task_runner | [AgentScheduler] Task queue is empty
2024-12-22 04:08:45,126 | sd | INFO | api | [AgentScheduler] Registering APIs
2024-12-22 04:08:45,493 | sd | DEBUG | webui | Scripts setup: ['IP Adapters:0.035', 'XYZ Grid:0.045', 'Ctrl-X: Controlling Structure and Appearance:0.009', 'DemoFusion: High-Resolution Image Generation:0.005', 'Face: Multiple ID Transfers:0.019', 'HDR: High Dynamic Range:0.006', 'K-Diffusion Samplers:0.103', 'LUT Color grading:0.008', 'Prompt enhance:0.005', 'Prompt matrix:0.005', 'Prompts from file:0.005', 'PuLID: ID Customization:0.008', 'Video AnimateDiff:0.008', 'Video CogVideoX:0.011', 'Video: ModelScope:0.006', 'LEdits: Limitless Image Editing:0.005', 'Video VGen Image-to-Video:0.009', 'Video: SVD:0.006']
2024-12-22 04:08:45,499 | sd | DEBUG | sd_checkpoint | Model metadata: file="metadata.json" no changes
2024-12-22 04:08:45,501 | sd | DEBUG | modeldata | Model requested: fn=run:<lambda>
2024-12-22 04:08:45,503 | sd | WARNING | sd_checkpoint | Cannot generate without a checkpoint
2024-12-22 04:08:45,504 | sd | INFO | sd_checkpoint | Set system paths to use existing folders
2024-12-22 04:08:45,505 | sd | INFO | sd_checkpoint |   or use --models-dir <path-to-folder> to specify base folder with all models
2024-12-22 04:08:45,507 | sd | INFO | sd_checkpoint |   or use --ckpt-dir <path-to-folder> to specify folder with sd models
2024-12-22 04:08:45,508 | sd | INFO | sd_checkpoint |   or use --ckpt <path-to-checkpoint> to force using specific model
2024-12-22 04:08:45,510 | sd | DEBUG | script_callbacks | Script callback init time: system-info.py:app_started=0.07 task_scheduler.py:app_started=0.38
2024-12-22 04:08:45,512 | sd | DEBUG | shared | Save: file="config.json" json=31 bytes=1290 time=0.002
2024-12-22 04:08:45,514 | sd | INFO | webui | Startup time: 11.96 torch=5.18 gradio=1.02 diffusers=0.15 libraries=1.39 extensions=0.91 detailer=0.09 ui-networks=0.23 ui-txt2img=0.21 ui-img2img=0.12 ui-control=0.20 ui-extras=0.05 ui-settings=0.52 ui-extensions=0.81 ui-defaults=0.08 launch=0.16 api=0.10 app-started=0.46
2024-12-22 04:08:45,523 | sd | INFO | webui | Launching browser
2024-12-22 04:08:49,753 | sd | INFO | server | MOTD: N/A
2024-12-22 04:08:53,006 | sd | DEBUG | theme | UI themes available: type=Standard themes=12
2024-12-22 04:08:53,754 | sd | INFO | api | Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
2024-12-22 04:10:00,199 | sd | DEBUG | launch | Server: alive=True requests=205 memory=0.66/15.93 status='idle' task='' timestamp=None id='' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=80 elapsed=74.7 eta=None progress=0
2024-12-22 04:12:00,098 | sd | DEBUG | launch | Server: alive=True requests=213 memory=0.66/15.93 status='idle' task='' timestamp=None id='' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=199 elapsed=194.6 eta=None progress=0
2024-12-22 04:14:00,000 | sd | DEBUG | launch | Server: alive=True requests=215 memory=0.66/15.93 status='idle' task='' timestamp=None id='' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=319 elapsed=314.5 eta=None progress=0
2024-12-22 04:15:59,902 | sd | DEBUG | launch | Server: alive=True requests=217 memory=0.66/15.93 status='idle' task='' timestamp=None id='' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=439 elapsed=434.4 eta=None progress=0
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by shazam1234raja** [comment]
I have been having the same issue 
I am using SD.next as you see in the picture 
1 generation takes with Width: 320 Height 320 takes more then 30mins

Running 
windows 10 pro
GPU - AMD Radeon RX 6600 XT
CPU - AMD Ryzen 5 5600 6-Core Processor
VRAM - 8176 MB GDDR6 2000 MHz
RAM - 16 GB



![image](https://github.com/user-attachments/assets/7a17dca7-0938-48ec-9c59-725ab0d391fe)

Starting SD.Next
17:26:35-998149 INFO     Logger: file="E:\Stable Diffusion\ZLUDA STABLE diffusion\automatic\sdnext.log" level=DEBUG
                         size=65 mode=create
17:26:36-000125 INFO     Python: version=3.10.6 platform=Windows bin="E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\venv\Scripts\python.exe" venv="E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\venv"
17:26:36-431118 INFO     Version: app=sd.next updated=2024-12-09 hash=a2f5a39a branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
17:26:37-020432 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6 docker=False
17:26:37-024286 DEBUG    Packages: venv=venv site=['venv', 'venv\\lib\\site-packages']
17:26:37-025287 INFO     Args: ['--use-zluda', '--debug', '--autolaunch']
17:26:37-027287 DEBUG    Setting environment tuning
17:26:37-028288 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
17:26:37-034289 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
17:26:37-045292 INFO     Python: version=3.10.6 platform=Windows bin="E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\venv\Scripts\python.exe" venv="E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\venv"
17:26:37-050315 INFO     ROCm: AMD toolkit detected
17:26:37-499652 INFO     ROCm: agents=['gfx1032']
17:26:37-501652 INFO     ROCm: version=6.2, using agent gfx1032
17:26:37-537660 WARNING  Failed to load ZLUDA: Could not find module 'E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\.zluda\nvrtc64_112_0.dll' (or one of its dependencies). Try using the full
                         path with constructor syntax.
17:26:37-539702 INFO     **Using CPU-only torch**
17:26:37-726465 INFO     Install: verifying requirements
17:26:37-730508 INFO     Verifying packages
17:26:37-817570 DEBUG    Timestamp repository update time: Mon Dec  9 13:57:14 2024
17:26:37-819571 INFO     Startup: standard
17:26:37-820571 INFO     Verifying submodules
17:26:43-252439 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
17:26:43-520436 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
17:26:43-522436 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
17:26:43-710877 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
17:26:43-984535 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
17:26:43-985536 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
17:26:44-176897 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
17:26:44-366913 DEBUG    Git submodule: modules/k-diffusion / master
17:26:44-638891 DEBUG    Git detached head detected: folder="wiki" reattach=master
17:26:44-640893 DEBUG    Git submodule: wiki / master
17:26:44-758919 DEBUG    Register paths
17:26:44-813931 DEBUG    Installed packages: 182
17:26:44-814931 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
17:26:44-970965 DEBUG    Extension installer: E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
17:26:46-277078 DEBUG    Extension installer: E:\Stable Diffusion\ZLUDA STABLE
                         diffusion\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
17:26:55-136993 DEBUG    ONNX: version=1.20.1 provider=CPUExecutionProvider, available=['AzureExecutionProvider',
                         'CPUExecutionProvider']
17:26:55-179003 INFO     **Device**:

**Comment by carcoonzyk** [comment]
I have been having the same issue

**with error**:
Failed to load ZLUDA: Could not find module 'F:\automatic\.zluda\nvrtc64_112_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### My solution：
I manually downloaded zluda for the corresponding rocm6.1 version ([https://github.com/lshqqytiger/ZLUDA/releases/download/rel.c0804ca624963aab420cb418412b1c7fbae3454b/ZLUDA-windows-rocm6-amd64.zip]) and set the environment variables set `ZLUDA=F:\zluda` (where I manually download the zluda.exe and decompress)starting with webui.bat. Then I succeeded

**Comment by lshqqytiger** [comment]
Should be fixed by recent merge #3642 
Please try again after wiping `.zluda` folder.

**Comment by vladmandic** [comment]
closing as this should be fixed in the latest version - if issue persists, report here and i'll reopen.

**Comment by normalfella112** [comment]
This issue is still happening to me.
Microsoft Windows [Version 10.0.19045.5608]
(c) Microsoft Corporation. All rights reserved.

E:\Anewforge\SD.NEXT\sdnext>.\webui.bat --use-zluda --debug --autolaunch
Using VENV: E:\Anewforge\SD.NEXT\sdnext\venv
03:41:46-292987 INFO     Starting SD.Next
03:41:46-297011 INFO     Logger: file="E:\Anewforge\SD.NEXT\sdnext\sdnext.log" level=DEBUG host="DESKTOP-3MTN287"
                         size=83 mode=create
03:41:46-300033 INFO     Python: version=3.11.9 platform=Windows
                         bin="E:\Anewforge\SD.NEXT\sdnext\venv\Scripts\python.exe"
                         venv="E:\Anewforge\SD.NEXT\sdnext\venv"
03:41:46-497354 INFO     Version: app=sd.next updated=2025-04-04 hash=8b73cb62 branch=master
                         url=https://github.com/vladmandic/sdnext/tree/master ui=main
03:41:47-232289 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.11.9 locale=('English_United States', '1252')
                         docker=False
03:41:47-239028 DEBUG    Packages: prefix=venv site=['venv', 'venv\\Lib\\site-packages']
03:41:47-241050 INFO     Args: ['--use-zluda', '--debug', '--autolaunch']
03:41:47-244067 DEBUG    Setting environment tuning
03:41:47-246036 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
03:41:47-257004 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
03:41:47-281944 INFO     ROCm: AMD toolkit detected
03:41:47-843560 INFO     ROCm: agents=['gfx1102']
03:41:47-846552 INFO     ROCm: version=6.2, using agent gfx1102
03:41:47-848548 INFO     Python: version=3.11.9 platform=Windows
                         bin="E:\Anewforge\SD.NEXT\sdnext\venv\Scripts\python.exe"
                         venv="E:\Anewforge\SD.NEXT\sdnext\venv"
03:41:49-297961 INFO     ZLUDA load: path='E:\Anewforge\SD.NEXT\sdnext\.zluda' nightly=False
03:41:49-300925 WARNING  Failed to load ZLUDA: Could not find module 'C:\Program Files\AMD\ROCm\6.2\bin\rocblas.dll'
                         (or one of its dependencies). Try using the full path with constructor syntax.
03:41:49-302920 INFO     Using CPU-only torch
03:41:49-448250 INFO     Install: verifying requirements
03:41:49-496925 DEBUG    Timestamp repository update time: Fri Apr  4 08:17:04 2025
03:41:49-498920 INFO     Startup: standard
03:41:49-499917 INFO     Verifying submodules
03:41:52-798141 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
03:41:52-880260 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
03:41:52-955459 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
03:41:53-067293 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
03:41:53-069288 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
03:41:53-147003 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
03:41:53-224797 DEBUG    Git submodule: modules/k-diffusion / master
03:41:53-298760 DEBUG    Git submodule: wiki / master
03:41:53-343668 DEBUG    Register paths
03:41:53-409492 DEBUG    Installed packages: 172
03:41:53-412483 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
03:41:53-613945 DEBUG    Extension installer:
                         E:\Anewforge\SD.NEXT\sdnext\extensions-builtin\sd-webui-agent-scheduler\install.py
03:41:56-203427 DEBUG    Extension installer:
                         E:\Anewforge\SD.NEXT\sdnext\extensions-builtin\stable-diffusion-webui-rembg\install.py
03:42:05-110273 DEBUG    Extensions all: []
03:42:05-113420 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
03:42:05-115416 INFO     Install: verifying requirements
03:42:05-116413 DEBUG    Setup complete without errors: 1744015325
03:42:05-121400 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
03:42:05-123395 INFO     Command line args: ['--use-zluda', '--debug', '--autolaunch'] autolaunch=True use_zluda=True
                         debug=True args=[]
03:42:05-127383 DEBUG    Env flags: []
03:42:05-128381 DEBUG    Starting module: <module 'webui' from 'E:\\Anewforge\\SD.NEXT\\sdnext\\webui.py'>
03:42:11-996949 INFO     Torch: torch==2.6.0+cpu torchvision==0.21.0+cpu
03:42:11-998918 INFO     Packages: diffusers==0.33.0.dev0 transformers==4.50.3 accelerate==1.6.0 gradio==3.43.2
                         pydantic==1.10.21
03:42:12-168723 DEBUG    Read: file="E:\Anewforge\SD.NEXT\sdnext\config.json" json=33 bytes=1483 time=0.000
                         fn=<module>:load
03:42:12-479928 INFO     Engine: backend=Backend.DIFFUSERS compute=cpu device=cpu attention="Scaled-Dot-Product"
                         mode=no_grad
03:42:12-484914 DEBUG    Read: file="html\reference.json" json=69 bytes=36430 time=0.000
                         fn=_call_with_frames_removed:<module>
03:42:12-487907 DEBUG    Torch attention: type="sdpa" flash=True memory=True math=True
03:42:12-491895 INFO     Torch parameters: backend=cpu device=cpu config=Auto dtype=torch.bfloat16 context=no_grad
                         nohalf=False nohalfvae=False upcast=False deterministic=False tunable=[False, False] fp16=pass
                         bf16=pass optimization="Scaled-Dot-Product"
03:42:12-781317 DEBUG    ONNX: version=1.21.0 provider=CPUExecutionProvider, available=['AzureExecutionProvider',
                         'CPUExecutionProvider']
03:42:12-866359 INFO     Device:
03:42:12-975096 DEBUG    Entering start sequence
03:42:12-979056 DEBUG    Initializing
03:42:12-981051 DEBUG    Read: file="metadata.json" json=1 bytes=97 time=0.000 fn=initialize:init_metadata
03:42:12-985040 DEBUG    Read: file="cache.json" json=1 bytes=186 time=0.000 fn=initialize:init_cache
03:42:12-988032 DEBUG    Huggingface cache: path="C:\Users\norma\.cache\huggingface\hub"
03:42:13-031044 INFO     Available VAEs: path="models\VAE" items=0
03:42:13-034035 INFO     Available UNets: path="models\UNET" items=0
03:42:13-036030 INFO     Available TEs: path="models\Text-encoder" items=0
03:42:13-039022 INFO     Available Models: safetensors="models\Stable-diffusion":1 diffusers="models\Diffusers":0
                         items=1 time=0.00
03:42:13-049994 INFO     Available LoRAs: path="models\Lora" items=0 folders=2 time=0.00
03:42:13-069887 INFO     Available Styles: path="models\styles" items=288 time=0.02
03:42:13-148063 INFO     Available Detailer: path="models\yolo" items=10 downloaded=0
03:42:13-151025 DEBUG    Extensions: disabled=['Lora', 'sdnext-modernui']
03:42:13-153019 INFO     Load extensions
03:42:13-866268 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py'
                         Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
03:42:13-873094 DEBUG    Extensions init time: total=0.72 sd-webui-agent-scheduler=0.58
03:42:13-884313 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000 fn=__init__:__init__
03:42:13-891879 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719
                         time=0.000 fn=__init__:find_scalers
03:42:13-896752 DEBUG    Available chaiNNer: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
03:42:13-901740 INFO     Available Upscalers: items=71 downloaded=0 user=0 time=0.02 types=['None', 'Resize', 'Latent',
                         'AsymmetricVAE', 'DCC', 'VIPS', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'RealESRGAN', 'SCUNet',
                         'Diffusion', 'SwinIR']
03:42:13-914705 DEBUG    UI start sequence
03:42:13-916707 INFO     UI locale: name="Auto"
03:42:13-923238 INFO     UI theme: type=Standard name="black-teal" available=13
03:42:13-932606 DEBUG    UI theme: css="E:\Anewforge\SD.NEXT\sdnext\javascript\black-teal.css" base="sdnext.css"
                         user="None"
03:42:13-940593 DEBUG    UI initialize: txt2img
03:42:13-981834 DEBUG    Networks: type="model" items=69 subfolders=4 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Diffusers', 'models\\Reference'] list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=8
03:42:13-989814 DEBUG    Networks: type="lora" items=0 subfolders=1 tab=txt2img folders=['models\\Lora'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=8
03:42:14-001810 DEBUG    Networks: type="style" items=288 subfolders=3 tab=txt2img folders=['models\\styles', 'html']
                         list=0.02 thumb=0.00 desc=0.00 info=0.00 workers=8
03:42:14-010757 DEBUG    Networks: type="embedding" items=0 subfolders=1 tab=txt2img folders=['models\\embeddings']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8
03:42:14-019821 DEBUG    Networks: type="vae" items=0 subfolders=1 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=8
03:42:14-024807 DEBUG    Networks: type="history" items=0 subfolders=1 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=8
03:42:14-508715 DEBUG    UI initialize: img2img
03:42:14-719569 DEBUG    UI initialize: control models="models\control"
03:42:14-907089 DEBUG    Script: fn="extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py"
                         type=control skip
03:42:15-171935 DEBUG    UI initialize: video
03:42:15-579870 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000 fn=__init__:read_from_file
03:42:15-586848 DEBUG    UI settings: sections=21 settings=517
03:42:16-069327 INFO     Extension list is empty: refresh required
03:42:16-673052 DEBUG    Extension list: processed=6 installed=6 enabled=4 disabled=2 visible=6 hidden=0
03:42:17-023730 DEBUG    Root paths: ['E:\\Anewforge\\SD.NEXT\\sdnext', 'models']
03:42:17-119948 INFO     Local URL: http://127.0.0.1:7860/
03:42:17-123955 DEBUG    API middleware: [<class 'starlette.middleware.base.BaseHTTPMiddleware'>, <class
                         'starlette.middleware.gzip.GZipMiddleware'>]
03:42:17-126240 DEBUG    API initialize
03:42:17-328846 INFO     [AgentScheduler] Task queue is empty
03:42:17-331742 INFO     [AgentScheduler] Registering APIs
03:42:17-618005 DEBUG    UI: connected
03:42:17-679811 DEBUG    Scripts setup: time=0.683 ['Face: Multiple ID Transfers:0.181', 'K-Diffusion Samplers:0.106',
                         'XYZ Grid:0.052', 'IP Adapters:0.048', 'Prompt enhance:0.026', 'Mixture-of-Diffusers: Tile
                         Control:0.024', 'FreeScale: Tuning-Free Scale Fusion:0.013', 'Video: LTX Video
                         (Legacy):0.013', 'ConsiStory: Consistent Image Generation:0.012', 'Video: CogVideoX
                         (Legacy):0.011', 'Video: AnimateDiff:0.011', 'Video: Allegro (Legacy):0.011']
03:42:17-689218 DEBUG    Model metadata: file="metadata.json" no changes
03:42:17-695237 DEBUG    Model requested: fn=run:<lambda>
03:42:17-698501 INFO     Load model: select="dreamshaper_8 [879db523c3]"
Progress  3.69it/s █████████ 100% 6/6 00:01 00:00 Loading pipeline components...
03:42:19-480936 DEBUG    Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.bfloat16, 'load_connected_pipeline': True, 'extract_ema': False,
                         'config': 'configs/sd15', 'use_safetensors': True, 'cache_dir':
                         'C:\\Users\\norma\\.cache\\huggingface\\hub'}
03:42:19-488915 INFO     Network load: type=embeddings loaded=0 skipped=0 time=0.00
03:42:19-491907 DEBUG    Setting model: component=VAE slicing=True
03:42:19-493902 DEBUG    Setting model: attention="Scaled-Dot-Product"
03:42:19-507864 DEBUG    Setting model: offload=none limit=0.0
03:42:19-713350 DEBUG    GC: current={'gpu': 0, 'ram': 2.67, 'oom': 0} prev={'gpu': 0, 'ram': 2.67} load={'gpu': 0,
                         'ram': 17} gc={'gpu': 0, 'py': 5321} fn=reload_model_weights:load_diffuser why=force time=0.20
03:42:19-721959 INFO     Load model: time=total=1.81 load=1.79 native=512 memory={'ram': {'used': 2.67, 'total':
                         15.91}}
03:42:19-732525 DEBUG    Script init: ['system-info.py:app_started=0.08', 'task_scheduler.py:app_started=0.35']
03:42:19-734521 DEBUG    Save: file="E:\Anewforge\SD.NEXT\sdnext\config.json" json=33 bytes=1433 time=0.002
03:42:19-736516 INFO     Startup time: total=33.80 torch=24.46 launch=19.36 installer=19.19 checkpoint=2.05 gradio=1.22
                         libraries=1.16 ui-extensions=1.12 extensions=0.72 ui-txt2img=0.45 app-started=0.44
                         ui-networks=0.36 ui-control=0.30 ui-defaults=0.28 ui-models=0.24 ui-img2img=0.17 api=0.12
                         diffusers=0.09 detailer=0.08 transformers=0.06 samplers=0.05
03:42:19-754468 INFO     Launching browser
03:42:22-866217 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/motd 127.0.0.1 0.6306
03:42:28-396183 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.001
03:42:32-503994 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;
                         rv:137.0) Gecko/20100101 Firefox/137.0
03:42:32-509978 INFO     API user=None code=200 http/1.1 GET /sdapi/v1/start 127.0.0.1 0.006
03:42:32-514964 INFO     UI: ready time=11.798
03:42:32-634644 DEBUG    UI: connected
