### ISSUE TITLE
[Issue]: FastYunhuan wrong download URL

### ISSUE THREAD

**Issue by holgerpieta** [vladmandic/automatic#3727]
### Issue Description

The original download problem has been solved, but now there is a new one:
```
18:47:49-179396 ERROR    Exception: 404 Client Error. (Request ID:
                         Root=1-6797c6c5-6bd46d6d688ddfef30e410da;7f686448-4354-4e13-a960-0750c0fbcdb4)

                         Entry Not Found for url:
                         https://huggingface.co/FastVideo/FastHunyuan/resolve/main/model_index.json.
```

### Version Platform Description

```
18:17:14-049580 INFO     Starting SD.Next
18:17:14-052659 INFO     Logger: file="D:\SD.Next\automatic\sdnext.log" level=DEBUG size=65 mode=create
18:17:14-053688 INFO     Python: version=3.11.9 platform=Windows bin="D:\SD.Next\automatic\venv\Scripts\python.exe"
                         venv="D:\SD.Next\automatic\venv"
18:17:14-289086 INFO     Version: app=sd.next updated=2025-01-25 hash=3f2c9c4e branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
18:17:14-815461 INFO     Updating main repository
18:17:17-846084 INFO     Repository upgraded: 63582764 Mon Jan 27 11:02:28 2025 -0500
18:17:17-856103 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.9 docker=False
18:17:17-856103 DEBUG    Packages: venv=venv site=['venv', 'venv\\Lib\\site-packages']
18:17:17-856103 INFO     Args: ['--use-zluda', '--debug', '--autolaunch', '--docs', '--upgrade', '--requirements']
18:17:17-856103 DEBUG    Setting environment tuning
18:17:17-856103 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
18:17:17-856103 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
18:17:17-874887 INFO     Python: version=3.11.9 platform=Windows bin="D:\SD.Next\automatic\venv\Scripts\python.exe"
                         venv="D:\SD.Next\automatic\venv"
18:17:17-879002 INFO     ROCm: AMD toolkit detected
18:17:18-290764 INFO     ROCm: agents=['gfx1102']
18:17:18-291790 INFO     ROCm: version=5.7, using agent gfx1102
18:17:19-389910 INFO     Using ZLUDA in D:\SD.Next\automatic\.zluda
No ROCm runtime is found, using ROCM_HOME='C:\Program Files\AMD\ROCm\5.7'
18:17:26-218103 INFO     Install: verifying requirements
18:17:26-226283 INFO     Startup: standard
18:17:26-226283 INFO     Verifying submodules
18:17:28-307693 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
18:17:28-902036 DEBUG    Git detached head detected: folder="extensions-builtin/sd-extension-system-info" reattach=main
18:17:28-902036 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
18:17:29-466566 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
18:17:30-009153 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / dev
18:17:30-522317 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
18:17:31-035968 DEBUG    Git submodule: modules/k-diffusion / master
18:17:31-601147 DEBUG    Git detached head detected: folder="wiki" reattach=master
18:17:31-601147 DEBUG    Git submodule: wiki / master
18:17:32-179003 DEBUG    Register paths
18:17:32-228878 DEBUG    Installed packages: 186
18:17:32-228878 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
18:17:32-694617 DEBUG    Git submodule: extensions-builtin\sd-extension-chainner / main
18:17:33-248266 DEBUG    Git submodule: extensions-builtin\sd-extension-system-info / main
18:17:33-814226 DEBUG    Git submodule: extensions-builtin\sd-webui-agent-scheduler / main
18:17:34-314162 DEBUG    Extension installer:
                         D:\SD.Next\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
18:17:38-209668 DEBUG    Git submodule: extensions-builtin\sdnext-modernui / dev
18:17:38-731343 DEBUG    Git submodule: extensions-builtin\stable-diffusion-webui-rembg / master
18:17:39-215068 DEBUG    Extension installer:
                         D:\SD.Next\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
18:17:45-812809 DEBUG    Extensions all: []
18:17:45-812809 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
```

### Relevant log output

```shell
18:47:49-179396 ERROR    Exception: 404 Client Error. (Request ID:
                         Root=1-6797c6c5-6bd46d6d688ddfef30e410da;7f686448-4354-4e13-a960-0750c0fbcdb4)

                         Entry Not Found for url:
                         https://huggingface.co/FastVideo/FastHunyuan/resolve/main/model_index.json.
```

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

Any Video Model

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this was fixed yesterday, please update.

**Comment by holgerpieta** [comment]
I'm afraid it is not fixed. Or there is something weird going on.
(And I'm apparently not allowed to reopen issues.)

I've pulled dev branch about an hour before posting the issue. I pulled again 5 minutes ago, no update. I tried again 4 minutes ago: Same error message.
The download error we talked about a couple of days ago is a different one. That download works now, but then it fails a couple of steps later trying to download some other file.

**Comment by vladmandic** [comment]
i'll check.
