### ISSUE TITLE
[Issue]: Lora and LyCORIS path configuration is no longer valid

### ISSUE THREAD

**Issue by tkiikt** [vladmandic/automatic#381]
### Issue Description

Lora and LyCORIS path configuration is no longer valid In Settings > System Path.

I have the following settings
`B:\SD\stable-diffusion-webui\models\Lora`

I got the following error
`Nothing here. Add some content to the following directories:
B:\SD\automatic\models\Lora`

<img width="552" alt="2023-04-23 001805" src="https://user-images.githubusercontent.com/129479703/233793287-6d1376ef-71dd-49ca-b3c2-c5375418e504.png">

### Version Platform Description

INFO     Python 3.10.9 on Windows
INFO     Running setup
INFO     Version: cb465b12 Sat Apr 22 09:37:17 2023 -0400
INFO     Updating Wiki
INFO     nVidia toolkit detected
INFO     Torch 2.0.0+cu118
INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

**Comment by shaneholloman** [comment]
Similar issue here for both of these dirs: Lora and LyCORIS.
Gui shows `C:\Users\shane\Documents\git\automatic\models\Lora` 
Path in settings however is set to `E:\ai\sd\stable-diffusion-webui\models\Lora\` in System Paths

**Comment by vladmandic** [comment]
fixed.

**Comment by ForceX34** [comment]
LyCORIS still appears to point to the default path even after setting a custom path.

**Comment by ForceX34** [comment]
> fixed.

LyCORIS still appears to point to the default path even after setting a custom path.

**Comment by vladmandic** [comment]
did you restart server?

**Comment by ForceX34** [comment]
Never mind working now. After updating to Version: ec532ee9 LyCORIS was still defaulting to default path until restarting server a few times. Not sure why it didn't take until a few fresh restarts after the update. It works now

**Comment by tkiikt** [comment]
> > fixed.
> 
> LyCORIS still appears to point to the default path even after setting a custom path.

I have confirmed that the fix is in, both LORA and LyCORIS path settings.
