### ISSUE TITLE
[Issue]: [model_name] bug in Images filename pattern

### ISSUE THREAD

**Issue by ostap667inbox** [vladmandic/automatic#399]
### Issue Description

A folder with models is specified in the settings. This folder contains various subdirectories with models.

Bug: if in the pattern of the image name specified parameter [model_name] then in addition to the name of the model in the file name is placed also the name of the directory.

**Bug example:**
File name pattern: _[datetime] - [model_name] - [seed]_
Path to model: _/Novel Inkpunk F222/Inkpunk-Diffusion-v2_0.75-f222_0.25.ckpt_

The resulting image name:
20230423114856 - Novel Inkpunk F222_Inkpunk-Diffusion-v2_0.75-f222_0.25 - 2185197133.png"

Should be:
20230423114856 - Inkpunk-Diffusion-v2_0.75-f222_0.25 - 2185197133.png

The original Automatic1111 WebUI does not have this bug.

### Version Platform Description

[4cb46d5](https://github.com/vladmandic/automatic/commit/4cb46d5400b04491ae9e70d992ca0019d48942a9)

**Comment by ostap667inbox** [comment]
Also, the folder name is included in the meta picture as well, attaching it to the model name
![bug](https://user-images.githubusercontent.com/123593542/233830822-a1c0cf73-99ab-4a7e-8b22-b26bd0ad1734.png)

**Comment by vladmandic** [comment]
should be fixed now, please test and reopen if needed.

**Comment by ostap667inbox** [comment]
The bug is still present:
[40184f9](https://github.com/vladmandic/automatic/commit/40184f9e0b25e795fd5b199f9952c75cf3c19602)

**Comment by vladmandic** [comment]
silly question, but you did update the repo?
i just tried setting filename pattern: `[model_name] - [seed]

and it created file `outputs/text/00000-v1-5-pruned-emaonly - 1278195023.jpg`  
(00000 is prepended because "Add number to filename when saving" is enabled)

**Comment by ostap667inbox** [comment]
I updated the repository. Current [40184f9](https://github.com/vladmandic/automatic/commit/40184f9e0b25e795fd5b199f9952c75cf3c19602)
Bug is still here.

Path to directory with stable diffusion checkpoints in Settings:
D:\install\NEURAL\MODELS

Model path:
D:\install\NEURAL\MODELS\Deliberate\deliberate_v2.safetensors

Image file name pattern:
[datetime] - [model_name] - [seed]

The folder name is still included in the picture filename and in the meta data.

Right now I generated a picture. The file name is:
"20230423171618 - Deliberate_deliberate_v2 - 1078381348.png" 

And this is a screenshot of the parameters in the meta-data file:
![bug](https://user-images.githubusercontent.com/123593542/233845214-b709a67a-578a-4d14-8946-e6db583d4422.png)

**Comment by vladmandic** [comment]
ahh, i understand.

your model path is `D:\install\NEURAL\MODELS`
your model name is `Deliberate\deliberate_v2.safetensors`

so path is not appended, what you'd like is to strip any path-like parts from model name. i don't want that, i believe current behavior is correct and deliberate.

**Comment by ostap667inbox** [comment]
It is normal when the `D:\install\NEURAL\MODELS` folder has subdirectories. 
For example, the subdirectory \Deliberate\ contains two models versions 1.1 and 2.0. Also there are stored notes about the model, examples of prompts, etc. And some subdirectories have a lot of files of different versions. It is a proper organization of files when all 350 model files are not piled in one folder.

I understand the point of view, but I don't agree with it. There is no good reason to inflate a model name by adding its subdirectory name to it.

And if the image filename pattern contains `[model_name]`, it is expected to result in "deliberate_v2", but not "Deliberate_deliberate_v2". No matter how it appears in the lists, the model name is not "Deliberate\deliberate_v2.safetensors" after all, but "deliberate_v2.safetensors" - according to the file name.

There was a similar issue with A1111 before, they fixed it now. I use both your build and theirs (model paths are the same).

**Comment by vladmandic** [comment]
can you point where it was "fixed" in a1111?
looking at:
<https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/22bcc7be428c94e9408f589966c2040187245d81/modules/images.py#L346>
and:
<https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/22bcc7be428c94e9408f589966c2040187245d81/modules/sd_models.py#L45>

the behavior is identical.

we can agree to disagree on what default should be
now, i can add another filename template variable, lets call it `[short_name]` that would be just the model name - if that's ok with you (and in that case, i'd also like to remove extension as that is not really relevant to model name)?

**Comment by vladmandic** [comment]
puting this to rest:

`[model_name] - [seed]` -> `00006-testfolder_rev-animated-v12 - 4267729087.jpg` (note folder `testfolder)`
`[model_shortname] - [seed]` -> `00007-rev-animated-v12 - 2886050551.jpg` (not no folder prefixed)

**Comment by ostap667inbox** [comment]
> now, i can add another filename template variable, lets call it `[short_name]` that would be just the model name - if that's ok with you (and in that case, i'd also like to remove extension as that is not really relevant to model name)?

Yes, [model_shortname] completely solves the problem. Thank you.
