### ISSUE TITLE
[Issue]: Can't click image to full screen after generation

### ISSUE THREAD

**Issue by slurpey** [vladmandic/automatic#443]
### Issue Description

Not sure if bug or feature.  After generating an image, clicking the result would make this image go into full screen - but the behavior at the moment is to move to next image.  I could only find this online as a [bug in automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8992) but this would be gretly appreciated (bad eye sight here).

Thanks and also thanks for an amazing web ui.

### Version Platform Description

tested on firefox, chrome - windows 11
updated: 2023-04-23
hash: 40184f9e
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: AMD64 Family 23 Model 49 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

**Comment by tkiikt** [comment]
This issue has been fixed in the latest version. you can try: webui.bat --upgrade

**Comment by vladmandic** [comment]
you adding `git pull` is very similar to what `--upgrade` flag would do (plus few other things). the fact that it reports errors, please check `setup.log` for details - i'd like to resolve those.

anyhow, that is separate - is the original issue resolved after you've updated?

**Comment by slurpey** [comment]
Still doesn't work on my side.  Tested on firefox, chrome and edge (which had never seen it before.  Also reverted to gradi/default in case this was the reason.
when clicking on images, it cycles through to the next one - it doesn't pop the image out to full screen.  Behavior happens on generation interfaces and in image browser too.
Thanks

**Comment by slurpey** [comment]
![image](https://user-images.githubusercontent.com/10026060/233997835-e55d393d-9212-4f01-8ed8-c8683896014b.png)
It gives me the same error

**Comment by slurpey** [comment]
Confirmed.  It is fixed.
