### ISSUE TITLE
[Issue]: Prompt tag weight doesn't really work 

### ISSUE THREAD

**Issue by ryukra** [vladmandic/automatic#574]
### Issue Description

So this isn't a bug thats related to this fork, but its unfixed for 6 months+ so I'm asking here in hope it might get fixed faster.. 

InvokeAI has this working and I think auto1111 broke it when 2.0 came.

(black:1.0) construction worker
![image](https://user-images.githubusercontent.com/5844962/234998216-103e6bea-d21c-459a-bf4c-b91198fb7ea2.png)

(black:0.3) construction worker
![image](https://user-images.githubusercontent.com/5844962/234998285-69240001-e4d9-49e8-acbf-509e03623e73.png)

Steps: 16, Sampler: Euler a, CFG scale: 6.5, Seed: 792223283, Size: 512x768, Model hash: 0a741fabc7, Model: hyperV1_v10, VAE: vae-ft-mse-840000-ema-pruned, Clip skip: 1, ENSD: 31337, Token merging ratio: 0.5, Token merging ratio hr: 0.5, Token merging random: True, Token merging merge cross attention: True, Eta: 0.05

**Comment by ryukra** [comment]
![image](https://user-images.githubusercontent.com/5844962/235071885-4df1c1ea-98f4-453f-bab9-aee9729b0dd0.png)

photo of a man -> photo of a (black:x.x) man -> photo of a black man
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 2683157076, Size: 512x512, Model hash: cc6cb27103, Model: v1-5-pruned-emaonly, Clip skip: 1

**Comment by ryukra** [comment]
I think most think it works but it doesn't really, there are some unanswered issues detailing it, but even after telling people they didn't believe me lol. 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6416

implementation of a comfyUI custom node has different token normalisation and weight interpretation modes:
https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb

InvokeAI code:
https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/backend/prompting/conditioning.py

**Comment by vladmandic** [comment]
yes, those are what i'm looking at to implement as alternative to toekn parser thats built-in a1111 - like i said, i took a look and it its really a hot mess of unparsable regex statements.

**Comment by radry** [comment]
I can confirm this issue. For text tokens the weight between 0.1 and 1 doesn't matter but above 1 it will change the result. This aparently only affects text tokens, not embeddings, which still change with different weight between 0 and 1.  

![tmpgd9tes3h](https://user-images.githubusercontent.com/8878118/235318696-3257abb9-2af2-4684-aa21-2b59275a53c0.png)  

![tmpcn759pv2](https://user-images.githubusercontent.com/8878118/235318700-9a5566cc-018c-4316-a463-ca20f56e247a.png)

Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 2683157076, Size: 512x512, Model hash: e6415c4892, Model: realisticVisionV20_v20

**Comment by FullBleed** [comment]
There was quite a "debate" on the comfy UI git about comparing tag weight in a1111 and comfy UI (which uses the invoke ai method).  

Might be worth taking a look at: https://github.com/comfyanonymous/ComfyUI/discussions/473

**Comment by radry** [comment]
> There was quite a "debate" on the comfy UI git about comparing tag weight in a1111 and comfy UI (which uses the invoke ai method).
> 
> Might be worth taking a look at: [comfyanonymous/ComfyUI#473](https://github.com/comfyanonymous/ComfyUI/discussions/473)

This makes me think that the "problem" with a1111 implementation is that it doesn't show much effect when the prompt is short and simple since there aren't enough tokens to average out the weight? Meaning with more complex prompts the "problem" described in this issue shouldn go away?

**Comment by cool-bigdogs-tshirt** [comment]
just started looking into this myself in comfyui, though weirdly it seems to not work with *embeddings* for me in comfy.

was adding prompt coloring and noticed an embedding doing *nothing* at 0.8, when it worked fine in this repo: 
![image](https://user-images.githubusercontent.com/131823432/236653818-c45a204a-4ed2-478c-9bb5-c698bfe5b0ca.png)

**Comment by DirtyHamster** [comment]
I'm thinking this might just be a model data error... I've noticed that some apply properly others don't. It's the same for ethnicity prompts in the same way. If they didn't train the data using the tags you can't apply the weights to them.

**Comment by vladmandic** [comment]
i still plan to implement alternative prompt parser, but in the meantime i've just did some major work on the existing one - it should solve this problem.

**Comment by ryukra** [comment]
Downweighting is still not really working.. ^^' Its still a big deal, or maybe I don't understand the full or compel parser.

**Comment by vladmandic** [comment]
Commenting on issue closed 6month ago and without any details does not do anything.

**Comment by ryukra** [comment]
Its basically the same problem nothing has changed. Everything here is still valid. I think the downweighting is creating embeddings of every tag then applying the weight or something like that. I'm not into the material and don't know why the full solution you made still don't allow it.
