### ISSUE TITLE
[Issue]: Error running extension installer \openOutpaint-webUI-extension\install.py

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#659]
### Issue Description

Today I started getting the error:

19:39:12-348564 ERROR    Error running extension installer:
                         C:\StableDiffusion\vladmandic\extensions\openOutpaint-webUI-extension\install.py

the problem persists after re-install, and does not occur in the automatic1111 branch.

checking the openoutpaint depot, they haven't updated in 3 weeks, so I believe it is an issue introduced in some recent change.

Attaching full setup.log, but the relevent bit is this:

```
Error in sys.excepthook:

Traceback (most recent call last):

  File "C:\StableDiffusion\vladmandic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook

    Traceback.from_exception(

  File "C:\StableDiffusion\vladmandic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception

    return cls(

  File "C:\StableDiffusion\vladmandic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__

    for suppress_entity in suppress:

TypeError: 'module' object is not iterable



Original exception was:

Traceback (most recent call last):

  File "C:\StableDiffusion\vladmandic\extensions\openOutpaint-webUI-extension\install.py", line 3, in <module>

    from modules import scripts

  File "C:\StableDiffusion\vladmandic\modules\scripts.py", line 6, in <module>

    from modules import paths, script_callbacks, extensions, script_loading, scripts_postprocessing, errors

  File "C:\StableDiffusion\vladmandic\modules\extensions.py", line 5, in <module>

    from modules import shared, errors

  File "C:\StableDiffusion\vladmandic\modules\shared.py", line 53, in <module>

    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])

  File "C:\StableDiffusion\vladmandic\modules\shared.py", line 53, in <genexpr>

    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])

  File "C:\StableDiffusion\vladmandic\modules\devices.py", line 61, in get_optimal_device

    return torch.device(get_optimal_device_name())

  File "C:\StableDiffusion\vladmandic\modules\devices.py", line 44, in get_optimal_device_name

    if shared.cmd_opts.use_ipex:

AttributeError: 'Namespace' object has no attribute 'use_ipex'. Did you mean: 'use_cpu'?
```

[setup.log](https://github.com/vladmandic/automatic/files/11363181/setup.log)

### Version Platform Description

Version: 4dc59419 Sun Apr 30 21:01:49 2023 -0400

windows 10, chrome

**Comment by vladmandic** [comment]
i just pushed update, hope it resolves this. update here if it doesn't and i'll reopen.

**Comment by crazygonuts** [comment]
Issue still occuring on Version: 75b741f1 Sun Apr 30 23:06:32 2023 -0400

attaching new setup.log
[setup.log](https://github.com/vladmandic/automatic/files/11363296/setup.log)

**Comment by vladmandic** [comment]
I'll have to take a second look tomorrow, it's too late now.

**Comment by vladmandic** [comment]
just pushed an update, hopefully it resolves it (hopefully as i cannot reproduce). if not, report here and i'll reopen.

**Comment by crazygonuts** [comment]
seems to be fixed now on d4a748d 👍
