### ISSUE TITLE
[Issue]: WARNING  Checkpoint not found: None

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#713]
### Issue Description

This error started showing up upon boot on the console:

`WARNING  Checkpoint not found: None`

It appears even on a fresh installation, with the "stable-diffusion" directory populated with models and a model being actively selected.

### Version Platform Description

2023-05-02
hash: eb03fce3

**Comment by ke1ne** [comment]
Yes, having this too on eb03fce3

**Comment by mark-wd** [comment]
Same issue as #710

**Comment by vladmandic** [comment]
should be fixed.
also fixed is applying correct model config when switching between similar-but-not-identical models as well as generally faster model load on startup (by at least few sec).

**Comment by JaidynCG** [comment]
Thank you! That fixed that problem, but I'm still getting an error after I updated to 6f976c35.

<img width="867" alt="Screenshot 2023-05-02 214611" src="https://user-images.githubusercontent.com/66656514/235819254-4a051230-b894-4e8e-b31a-7ff60143ad15.png">

Just a side note: From what I've tested so far this fork seems way faster, wanted to thank you for being so dedicated to it! 💖

**Comment by vladmandic** [comment]
thanks for the comment!

your current issue is unrelated - it seems that safetensors cannot read your `revAnimated_v121` model.
can you try using `--ckpt <path_to_model_file>` to force-load any other model?

also, did you enable Settings -> Stable Diffusion -> When loading models attempt stream loading... ?
it seems it uses that code-path when there is no reason to do stream loading unless you forced it to?
