### ISSUE TITLE
[Issue]: Generate button stop working

### ISSUE THREAD

**Issue by merodiro** [vladmandic/automatic#779]
### Issue Description

Generate button stops working after generating images for some time and I need to refresh the browser to get it to work again
When it stops working I can still navigate to other tabs and use them to generate images
I don't see any errors in the terminal and this is my browser output

![image](https://user-images.githubusercontent.com/17033502/236550284-3d57fe0f-27e3-425e-82ff-4726284d0192.png)

I have this issue with automatic1111 and anapnoe's repo too. so this is probably caused by a problem upstream

### Version Platform Description

OS: Ubuntu
Browser: Chrome

**Comment by crazygonuts** [comment]
Ive experienced thia primarily when working remotely through the gradio share link, it seems to be some kind of race condition where if you click generate before it has finished downloading the images from the previous generate it will break

**Comment by vladmandic** [comment]
@crazygonuts i know what you mean and thats definitely an ongoing issue. this is a subset of it i can actually take care of so i prefer to have it separate.

**Comment by merodiro** [comment]
Yeah, I'm accessing it mostly remotely

**Comment by anapnoe** [comment]
this function triggers  the backend to get the image dimensions multiplied by the scale factor without the need to process anything this kind of approach can cause delays and bugs that wouldn't exist if the frontend do the work @vladmandic we need to move this staff to the frontend it will make the ui more performant and less prone to this king of bugs can you create a label `transfer to frontend` or something similar to mark things out?

**Comment by vladmandic** [comment]
bigger issue with generate doing round trips is handled separately.
original problem for this issue is with `prompt_bracket_checker` function and that has been resolved - please upgrade.

**Comment by merodiro** [comment]
I upgraded but the issue still happens sometimes and isn't solved completely. I think it happens less frequently now

**Comment by merodiro** [comment]
I'm not sure if this is relevant but I got a different error in the browser console this time
![image](https://github.com/vladmandic/automatic/assets/17033502/71cf1969-c3aa-4ebc-b32e-a811222ddb6a)
