### ISSUE TITLE
[Extension]: sd-webui-aspect-ratio-helper not showing

### ISSUE THREAD

**Issue by froger-me** [vladmandic/automatic#823]
### Issue Description

Extension: https://github.com/thomasasfk/sd-webui-aspect-ratio-helper
Version: b03cce20 (Mon Apr 10 21:17:00 2023) | latest

Settings are showing as intended:

<img width="120" alt="Screenshot 2023-05-09 at 8 34 42 AM" src="https://user-images.githubusercontent.com/3622456/236965121-ce2816c5-41e7-45f5-ae14-7c56b9416933.png">

UI is **not** showing:

<img width="661" alt="Screenshot 2023-05-09 at 8 34 25 AM" src="https://user-images.githubusercontent.com/3622456/236965138-c36a2397-fd55-4bc6-a277-224f925e3935.png">

### Version Platform Description

Version: 4d9fab4 Mon May 8 11:56:59 2023 -0400

**Comment by brknsoul** [comment]
I have a similar problem, but instead of the switch arrows, I used to get the dropdown, now I get nothing. o.O

**Comment by ariffammobox** [comment]
Yeah can verify as my last version `22e58809` on another machine still have the aspect ratio dropdown button.

**Comment by Averytingwong** [comment]
I use this thing a lot...where you go?!

**Comment by ariffammobox** [comment]
Apparently when using **Image-To-Image** the extension still works.

**Comment by froger-me** [comment]
```
2aspectRatioController.js?1683592293.2655532:378 Uncaught TypeError: Cannot read properties of undefined (reading 'arh_javascript_aspect_ratio_show')
    at MutationObserver.<anonymous> (aspectRatioController.js?1683592293.2655532:378:34)
(anonymous) @ aspectRatioController.js?1683592293.2655532:378
```

Finally got some time to check. Unsure whether it's this repo's issue or the extension's. Will dig.

**Comment by froger-me** [comment]
Created a pull request https://github.com/vladmandic/automatic/pull/827

**Comment by brknsoul** [comment]
> Created a pull request #827

If I changed the line in `ui.js` myself locally, would that work without having to wait for the request?

**Comment by vladmandic** [comment]
i'll merge it as soon as github is stable, currently there are some outages on github.

**Comment by brknsoul** [comment]
That gives me the dropdown;
![image](https://github.com/vladmandic/automatic/assets/1969381/6f056a21-b2ac-4513-84ad-d6d4e3a33d4c)

But I'm still missing the switch button.

**Comment by mark-wd** [comment]
I was having the same issue, but it has been fixed in gradio-default as of the latest version.

**Comment by vladmandic** [comment]
what is the current status? as far as i understand, it works fine with `gradio-default` theme, but some elements are not showing when using `black-orange` theme? which elements?

**Comment by vladmandic** [comment]
fixed.

**Comment by brknsoul** [comment]
Not fixed.
All themes now only show the switch button, but not the drop-down;
![image](https://github.com/vladmandic/automatic/assets/1969381/e883f33b-d947-4484-a0af-ec0afb6a01ad)
![image](https://github.com/vladmandic/automatic/assets/1969381/b30bed04-290f-4a53-8407-cf45df1cf799)
![image](https://github.com/vladmandic/automatic/assets/1969381/85665208-135e-4579-b9b9-663d1e8e054f)

**Comment by brknsoul** [comment]
This has disappeared again in version 5250ba4b !

**Comment by vladmandic** [comment]
general switch button is not hidden by css. and if it dissapeared in extension even when you're not using black-orange, then its not up to my css. i cant go chasing down which css extension uses - if somebody does it, great.

**Comment by brknsoul** [comment]
Sorry, not the switch button, the drop down;
![image](https://github.com/vladmandic/automatic/assets/1969381/4797cefa-530a-4633-aa21-29d763ae48c9)

**Comment by vladmandic** [comment]
Can you find that CSS rule (assuming it's about CSS)?

**Comment by brknsoul** [comment]
I have no idea on how to find that. Never did any web dev/CSS, sorry!

I'm only reporting what's missing.

**Comment by brknsoul** [comment]
(Psst.. this is closable ;-) )

**Comment by vladmandic** [comment]
thanks

**Comment by warudokiruhya** [comment]
I use the default version. It was there a minute ago and now its gone. I uninstalled and installed again, restarted, still nothing.
